### ISSUE TITLE
Reference methods on actors by index, not name

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#101]
Referencing the methods by name is currently only done as a simplifying measure to make development a bit easier in the short term. We should soon switch to using the index of the method within the actors method set as the 'method ID' in messages. The tooling can handle conversion from the string form to the integer form for the user, but the underlying message data structure should not contain human readable strings like that.

**Comment by pooja** [comment]
This issue encompasses work that needs to happen in spec and in gfc
