### ISSUE TITLE
Lotus is actually multiple repos

### ISSUE THREAD

**Issue by daviddias** [filecoin-project/specs#1037]
See: https://github.com/filecoin-project/lotus#packages

Can you list them all on the impl table at https://beta.spec.filecoin.io/#implementations-status ?

**Comment by olizilla** [comment]
Ok, how about

| Project | Module | Language | CI | Test Coverage   | Last Security Audit
|--------|---------|-----------|---|-----------------|--------------
| Lotus   | lotus      | go             | ✅ |31%                  | None
|             | storage-fsm  | go             | ✅ | xx%                  | None
|             | sector-storage  | go             | ✅ | xx%                  | None
|             | go-fil-markets   | go             | ? | Unknown                  | None
|             | specs-actors     | go             | ✅ | 71%                  | None
|             | sector-storage  | go             | ✅ | xx%                  | None
| go-filecoin  | go-filecoin | go     | ❌| 48%                  | None
| Forest          | forest        | rust   | ? | Unknown | None
| Fuhon          | fuhon        | c++   | ✅ | 35%       | None

**Comment by olizilla** [comment]
perhaps some of the modules are shared between go-filecoin and lotus, perhaps the module column is not needed.

**Comment by daviddias** [comment]
I like the module column.

In an ideal world, we have a way to reduce all the coverage and audits to a single value, for now, let's keep it expanded, even if it means having rows duplicated (which is not the case at the moment)

**Comment by olizilla** [comment]
🎉 
<img width="825" alt="Screenshot 2020-08-05 at 15 29 47" src="https://user-images.githubusercontent.com/58871/89425154-8c45ad00-d730-11ea-9daa-9b750ed53a85.png">

**Comment by olizilla** [comment]
Do we need to include the rust proofs lib too? https://github.com/filecoin-project/rust-fil-proofs Would that be assigned to Lotus or another?

**Comment by daviddias** [comment]
@olizilla let's stick it in Lotus

btw, can we make it so that the Lotus cells are vertically merged, so that the name isn't repeated in every single row?

**Comment by olizilla** [comment]
🌮 

<img width="826" alt="Screenshot 2020-08-05 at 20 25 09" src="https://user-images.githubusercontent.com/58871/89455186-cf684600-d759-11ea-9eb4-1c60e4c3de6f.png">

**Comment by anorth** [comment]
_All_ of the modules are used by Go-filecoin. That's why they're modules! It's quite misleading to consider them part of Lotus unless you're just ignoring Go-filecoin. They should all be duplicated if you're attempting to reflect the dependencies.

This is missing many transitive dependencies of both, but I'm not sure how deep you intend to go. Should probably include HAMT, AMT, Bitfield, Address at least.

Also there's nothing wrong with [Go-filecoin CI](https://circleci.com/gh/filecoin-project/go-filecoin) when I look at it.

**Comment by olizilla** [comment]
Simplest fix here is to just remove the project column, and rename the "module" column to be "Repo" or similar, as the entries in the current module column link to the repo.

This is supposed to be an informative overview of where we are at, to help people figure out what where the most significant gaps are. If there are dependencies you feel would be good to include here, please list them and I'll include them.

> Also there's nothing wrong with Go-filecoin CI when I look at it.

Right now the CI status is pulled at build time from the codecov.io api. We'll have a github action to update it hourly.

**Comment by olizilla** [comment]
the go-filecoin CI isn't completely satisfied... the badge on the repo says build failed, and the github statuses on the latest commit include 2 that fail.
