### ISSUE TITLE
Separate the Name from Language

### ISSUE THREAD

**Issue by daviddias** [filecoin-project/specs#1038]
An implementation of Filecoin is composed of multiple repos, sometimes they are implemented in different languages. Can you break the first column into two

![image](https://user-images.githubusercontent.com/1211152/89164329-3aa5f280-d577-11ea-84cb-a38726146782.png)

This will be useful when listing all the packages for #1037

**Comment by olizilla** [comment]
@daviddias agree. I'm going to leave the name of go-filecoin as `go-filecoin` as that is how it's always been referred to. 

e.g:

| Name | Language |
|-------------|-----------|
| lotus            | go             |
| go-filecoin  | go     |
| forest          | rust   |
| fuhon          | c++   |

**Comment by daviddias** [comment]
yeah, go-filecoin is indeed named go-filecoin (I did propose to name it "iceberg" so that we could use a _lettuce_ as a logo and with the iceberg name suggesting it is a thing of long lived storage (resembling glacier), but that did not fly, unfortunately, such a shame, was such a good name 😅)
