### ISSUE TITLE
Spec Content Structure

### ISSUE THREAD

**Issue by hugomrdias** [filecoin-project/specs#1073]
After doing this PR [https://github.com/filecoin-project/specs/pull/1071](https://github.com/filecoin-project/specs/pull/1071) to fix the dashboard numbering, we started discussing how to better structure the content, to be easier to work with and make custom UIs like the dashboard.

So first lets define some concepts so everyone can understand our ideas better.

## Sections

Sections are basically headings in a markdown file but when you start looking at the ToC tree and the numbering you see the parent/child relations, but a child/sub section can come from a H2 inline in the parent markdown file or a new file below the parent in the Hugo filesystem. So basically headings like H1, H2, etc, HTML tags don’t exactly map to the ToC tree directly.

<img width="537" alt="Screenshot 2020-08-20 at 16 08 38" src="https://user-images.githubusercontent.com/314190/90795982-a4a7f100-e306-11ea-8914-6be82a2ad8f8.png">
<img width="668" alt="Screenshot 2020-08-20 at 16 14 01" src="https://user-images.githubusercontent.com/314190/90795987-a5d91e00-e306-11ea-8e72-d11e4c070cd4.png">

## File

File is just a file in Hugo's filesystem, normally a markdown file, but it can hold **data** in the frontmatter like the dashboard values (weight, audits, tests, etc) plus other resources from the Hugo internal system. Files are normally represented in the ToC by the first H1 in the content and can have other sub sections using H2, H3, H4 etc.

## ToC

The table of contents is built by parsing all the sections either inline in the parent file or in a new file, normalising those, and creating the tree structure plus the numbering.

# The problem

Our current ToC is huge and we need to create UIs using the sections and some data. 

- Currently we can only have data inside the scope of a file and NOT per section.
- Including all the sections in a visualization is normally too much and not useful. (one example is the dashboard)

# Solutions

1. Only use the top level section of each file, effectively excluding inline sub sections because when it comes to data they just inherit the data from the file they are in, which is already represented by first H1 of the file.
2. Include all the sections and inline sub sections inherit the data from the file they are in.
    - We can manually cherry pick sections to be hidden
    - Filtering by depth is not a good solution to decrease the size, because the depth of the top level sections varies wildly
3. Add support for custom data in all the section either inline a parent or in a new file.
    - This needs a custom shortcode to write headings
    - Normal markdown heading syntax would need to be blocked by the system or else it would break the numbering
    - All the current heading would need to be written to use the custom shortcode.

  

We would like to go with solution 1 because it creates a more organic way to group concepts, one concept maps to one file and one set of related data. We can still have multiple sub sections inside a file and have the ToC exactly like we have now but when creating visualisations that need the related data we only use the top level section for each file. 

This solution will also "force" us to review the current folder/file structure to better group content and probably merge some files into a single file. We feel that this is actually a good thing and will make the repo even more approachable. 

Lastly solution 1 doesn't require any custom shortcode and is the easiest for people writing content.

We would like feedback on topic, so we can make the best decision for the Spec future.
/cc @yiannisbot @daviddias @nicola

**Comment by nicola** [comment]
Should we instead merge the multiple files into single files? This may also bring clarity of where to edit what for spec editors

**Comment by hugomrdias** [comment]
yes that what we want to do with solution 1

> This solution will also "force" us to review the current folder/file structure to better group content and probably merge some files into a single file. We feel that this is actually a good thing and will make the repo even more approachable.

tip: if you look at the perma link of a section you can map that directly to the filesystem
