### ISSUE TITLE
Requested Dashboard UI Tweaks

### ISSUE THREAD

**Issue by olizilla** [filecoin-project/specs#1098]
- [x] update legend text
- [x] make background for n/a for audit white.
- [x] show audit as WIP when audit is not yet published
- [x] show no audit yet as "Missing"
- [x] support links to multiple audits
- [x] link to multiple proofs audits
- [x] show entire table in page (no scrollbar, and dont break link positioning)
- [x] dont show text for n/a and None
- [x] hide weight column

**Comment by olizilla** [comment]
Linking to multiple audits:
<img width="1029" alt="Screenshot 2020-08-26 at 12 11 11" src="https://user-images.githubusercontent.com/58871/91296917-49a64c00-e795-11ea-8fcb-8890b1e4ab44.png">

**Comment by daviddias** [comment]
### New request: Make non actionable cells less verbose

![image](https://user-images.githubusercontent.com/1211152/91298342-c4706680-e797-11ea-9dab-c917512eceaa.png)

**Comment by olizilla** [comment]
@daviddias in the last case, where a security audit is missing, I've changed it so it says "Missing" and the background is red. Is good? I can make the bg white and remove the text if that is preferable.
<img width="1016" alt="Screenshot 2020-08-26 at 12 18 20" src="https://user-images.githubusercontent.com/58871/91300442-2ed6d600-e79b-11ea-8ef5-7f83ae155f4a.png">

**Comment by olizilla** [comment]
@daviddias i'm hiding the weight column from the spec state table. I'm inclinde to also hide the CI column from the implementations table as builds will occasionally fail, but it seems less interesting in this context than the test coverage and security audit info.
