### ISSUE TITLE
Does spec.filecoin.io load fast enough?

### ISSUE THREAD

**Issue by olizilla** [filecoin-project/specs#1142]
@daviddias @momack2 have reported slow loading for spec.filecoin.io site. If it happens for again, or for anyone else, please share the response headers for the html page request from the dev-tools network tab, along with any other relevant info to help debug.

**Comment by momack2** [comment]
I can no longer reproduce it: 
![image](https://user-images.githubusercontent.com/618519/92045140-afb24680-ed34-11ea-9a14-13bf53ff0307.png)
![image](https://user-images.githubusercontent.com/618519/92045225-de302180-ed34-11ea-97cf-74632779d70f.png)

**Comment by daviddias** [comment]
I only experienced the slowness in beta.spec.filecoin.io, the https://spec.filecoin.io/ is loading SUPA FAST for me :D

**Comment by thattommyhall** [comment]
I've been using https://chrome.google.com/webstore/detail/fhfgegloanobkdlkicjoefpnlbclfebg in chrome, I dont think you see headers in the inspector for requests before you opened it? 

This has also made me more aware of redirects too, pruned some unnecessary ones of ours 

(just example from the current request)

![Screenshot from 2020-09-03 14-36-28](https://user-images.githubusercontent.com/128916/92115602-fb2b2a00-edf2-11ea-9d33-36db3c0de2a2.png)

![Screenshot from 2020-09-03 14-36-48](https://user-images.githubusercontent.com/128916/92115607-fd8d8400-edf2-11ea-9596-a078890d5eae.png)
