### ISSUE TITLE
Host compiled spec output for public consumption

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#118]
When specs are released to the public, we should host the compiled Gitbook HTML and PDF outputs so that readers don't need to install npm, gitbook etc to get a good navigation experience. This is broken out from #113.

Possibly something as simple as pointing to CircleCI build outputs would suffice.

## Acceptance
- Up-to-date HTML and PDF outputs are available on the public internet with a stable URL.
- Not manual step is required to publish new outputs when the non-draft specs are updated.

**Comment by pooja** [comment]
Hey all. I put together an early version of this here: https://filecoin-1.gitbook.io/spec/

Once we finalize the structure for the Filecoin website and the documentation site, I will set this up at a custom domain.

Please provide feedback so we can make this better!

**Comment by gnunicorn** [comment]
>Hey all. I put together an early version of this here: https://filecoin-1.gitbook.io/spec/
Thanks! Am I mistaken or doesn't this provide PDF yet?

**Comment by pooja** [comment]
Sorry for the delay in response @gnunicorn. You are correct, it does not provide PDF 🤦‍♀️. Will look into that!

**Comment by dignifiedquire** [comment]
we now host the spec at https://filecoin-project.github.io/specs/

**Comment by dignifiedquire** [comment]
and the pdf output is tracked here: #266
