### ISSUE TITLE
Under what circumstances does the submitPoSt message contain non-empty 'recovered' and 'done' SectorSet?

### ISSUE THREAD

**Issue by laser** [filecoin-project/specs#120]
The [`submitPoSt`](https://github.com/filecoin-project/specs/blob/master/actors.md#submitpost) message includes `recovered` and `done` parameters of type `SectorSet`. `SectorSet` is currently defined in the spec as [`TODO`](https://github.com/filecoin-project/specs/blob/master/actors.md#sectorset).

Couple of questions about `submitPoSt`:

1) What's a `SectorSet`? Is it just a set of sector ids?
2) Under what circumstances is `done` non-empty?
3) Under what circumstances is `recovered` non-empty?

cc @whyrusleeping @ZenGround0

**Comment by pooja** [comment]
Document in the spec
