### ISSUE TITLE
Given that sector id is an input to the seal operation, how could it be returned from Actor#CommitSector?

### ISSUE THREAD

**Issue by laser** [filecoin-project/specs#121]
The [proofs](https://github.com/filecoin-project/specs/blob/master/proofs.md#seal) section of the spec shows that sector id is an input to the seal operation.

The [actors](https://github.com/filecoin-project/specs/blob/master/actors.md#commitsector) section of the spec shows that sector id is an output of the `CommitSector` method.

The seal operation must be run before `CommitSector` is called, and thus the sector id corresponding to any given CommR is determined before `CommitSector` is called.

Questions:

1) Shouldn't sector id be an _input_ to the `CommitSector` method instead of an output?

cc @whyrusleeping @ZenGround0

**Comment by pooja** [comment]
@laser Can this issue be closed as well then (since we just closed the PR)?

**Comment by pooja** [comment]
@laser Closing this, but feel free to reopen if needed
