### ISSUE TITLE
Discussion about how base fee reflects network congestion

### ISSUE THREAD

**Issue by nighca** [filecoin-project/specs#1257]
From specs we know that base fee change is determined by the average block gas limit of the previous epoch. The next base fee can be calculated like this:

```
delta_base_fee = base_fee * (block_gas_limit - target_block_gas_limit) / target_block_gas_limit / 8
next_base_fee = base_fee + delta_base_fee
```

Note that `block_gas_limit` is not the average value of every block's gas limit, because every message counts only once in one epoch, which means, the higher message repetition rate is, the lower final `block_gas_limit` will be. We can simply describe the relationship as this:

```
block_gas_limit = block_gas_limit_undeduped * (1 - messageRepetitionRate)
```

I collected block gas limit & gas data from `2021.05.14 00:00:00Z` to `2021.05.14 01:00:00Z`:

| height | block_gas_limit_undeduped | block_gas_limit | delta_base_fee | base_fee_change_ratio  |
| ------ | ------------------------- | --------------- | -------------- | ---------------------- |
| 754800 | 9984126394                | 6452162546      | 74323709       | 0.03630406365          |
| 754801 | 9992036210                | 4245501543      | -40018214      | -0.018862461425        |
| 754802 | 9611133913                | 3726012305      | -66297090      | -0.031849692375        |
| 754803 | 9998901256                | 4293408327      | -35599224      | -0.01766479181875      |
| 754805 | 9988458890                | 4852943860      | -7278048       | -0.0036764035125       |
| 754806 | 9997104421                | 4372631796      | -30935323      | -0.015684205108333325  |
| 754807 | 9959631996                | 9959631996      | 240722151      | 0.1239907999           |
| 754808 | 9997782727                | 6183164640      | 64546774       | 0.02957911599375       |
| 754809 | 9955346786                | 7653238682      | 149027153      | 0.0663309670375        |
| 754810 | 9988666742                | 6629844539      | 97617411       | 0.04074611346666668    |
| 754811 | 9996605285                | 4530902766      | -29240768      | -0.011727430858333325  |
| 754812 | 9965962372                | 8023818186      | 186276607      | 0.07559545465          |
| 754813 | 9988206708                | 3545161545      | -96397634      | -0.03637096138214285   |
| 754814 | 9258364181                | 3880930922      | -71452656      | -0.02797672694375      |
| 754815 | 9998952134                | 5498152704      | 30917234       | 0.0124538176           |
| 754816 | 9980495791                | 5436758943      | 27444490       | 0.01091897358499999    |
| 754817 | 9995132767                | 3792317118      | -76715412      | -0.030192072039999997  |
| 754818 | 9988901922                | 5010141940      | 624793         | 2.5354849375E-4        |
| 754819 | 9997677275                | 4279102189      | -44422117      | -0.018022445270000003  |
| 754820 | 7148098061                | 7148098061      | 129981399      | 0.053702451525         |
| 754821 | 9987490712                | 3860720544      | -72639921      | -0.0284819864          |
| 754822 | 9988496776                | 5496529362      | 30756782       | 0.01241323405          |
| 754823 | 9998611968                | 4794612722      | -12880339      | -0.00513468195         |
| 754824 | 9998824206                | 6883370432      | 117504312      | 0.0470842607875        |
| 754825 | 9994929692                | 4004987087      | -65002252      | -0.024875322833333338  |
| 754826 | 9993010005                | 6378030791      | 87784686       | 0.034450769775         |
| 754827 | 9990548230                | 3318545280      | -110803847     | -0.042036367991666664  |
| 754828 | 9420534111                | 3059874999      | -122475268     | -0.04850312502916666   |
| 754829 | 9983338744                | 3197290499      | -108280886     | -0.045067737525        |
| 754830 | 9469033828                | 3403314631      | -91583653      | -0.039917134220000004  |
| 754831 | 9981665153                | 3538425045      | -80487498      | -0.03653937386428572   |
| 754832 | 9105112821                | 2694586481      | -122317936     | -0.0576353379875       |
| 754833 | 9990374332                | 5399403351      | 19969721       | 0.009985083775         |
| 754834 | 9979231177                | 4333374496      | -33663338      | -0.016665637595000005  |
| 754835 | 9990355971                | 2282855437      | -134924004     | -0.06792861408055556   |
| 754836 | 9877655827                | 3113264805      | -87324599      | -0.04716837987916666   |
| 754837 | 9998246937                | 5062674719      | 2763976        | 0.00156686796875       |
| 754838 | 9997776230                | 5011171765      | 493450         | 2.7929411500000954E-4  |
| 754839 | 9980102447                | 8136646327      | 138582564      | 0.0784161581625        |
| 754840 | 9993620573                | 6447521735      | 68969094       | 0.0361880433625        |
| 754841 | 9976596740                | 4799463100      | -9900618       | -0.00501342250999999   |
| 754842 | 9991236919                | 6506114331      | 73984913       | 0.037652858275         |
| 754843 | 9768115401                | 3982522423      | -51863540      | -0.025436939425        |
| 754844 | 9623284986                | 2530335345      | -122683242     | -0.06174161637857143   |
| 754845 | 9995436171                | 5036934150      | 1721463        | 9.233537375E-4         |
| 754846 | 9979564513                | 4913911316      | -4016212       | -0.0021522171          |
| 754847 | 9559900347                | 3989011719      | -47063145      | -0.025274707020000006  |
| 754848 | 9733930286                | 3823132869      | -53400398      | -0.029421678264999997  |
| 754849 | 9998770578                | 5989930451      | 43596571       | 0.024748261283333326   |
| 754850 | 9998020958                | 4226130308      | -34924700      | -0.0193467423          |
| 754851 | 9980920946                | 6172035603      | 51870582       | 0.029300890066666675   |
| 754852 | 9995919701                | 3967451701      | -47036288      | -0.025813707478571427  |
| 754853 | 9983706638                | 3478635725      | -67514630      | -0.03803410687142857   |
| 754854 | 9981735864                | 3801528531      | -51162535      | -0.029961786725        |
| 754855 | 9998999251                | 7177860744      | 90186867       | 0.0544465185875        |
| 754856 | 9990098179                | 3727453109      | -55566309      | -0.0318136722875       |
| 754857 | 9987178670                | 3089498989      | -80768863      | -0.047762525265625     |
| 754858 | 9991168080                | 3374085596      | -65454520      | -0.04064786010714285   |
| 754859 | 9980705764                | 5401270800      | 15497355       | 0.01003176999375       |
| 754860 | 9450421288                | 3107406285      | -73826528      | -0.047314842882142855  |
| 754861 | 9998862873                | 4999431437      | -21416         | -1.42140875E-5         |
| 754862 | 9987230643                | 4394043186      | -19703990      | -0.01514892035         |
| 754863 | 9984383317                | 3663799905      | -44359548      | -0.03340500236388888   |
| 754864 | 9996069877                | 3954475490      | -33760670      | -0.02613811275833334   |
| 754865 | 9994856239                | 2864177843      | -67230109      | -0.0533955539175       |
| 754866 | 9998916295                | 4149963740      | -25346552      | -0.021250906495000006  |
| 754867 | 9982983983                | 6057532279      | 30863589       | 0.0264383069625        |
| 754868 | 9999184509                | 6312023906      | 39303154       | 0.03280059765          |
| 754869 | 9991573211                | 3103991016      | -58660063      | -0.047400224605555555  |
| 754870 | 9979174239                | 6208083210      | 35604874       | 0.03020208025          |
| 754871 | 9977612618                | 4488193587      | -15539633      | -0.012795160325        |
| 754872 | 9995827759                | 6170821172      | 35094000       | 0.029270529308333324   |
| 754873 | 9998745551                | 5322573307      | 9951769        | 0.008064332675         |
| 754874 | 9998965087                | 5603846456      | 18779612       | 0.0150961614           |
| 754875 | 9988590261                | 7678714090      | 84565582       | 0.06696785225          |
| 754876 | 9962604693                | 6761002428      | 59316916       | 0.04402506070625       |
| 754877 | 9998284800                | 5754330401      | 26527184       | 0.018858260025         |
| 754878 | 9974834479                | 3103460507      | -67952462      | -0.04741348733125      |
| 754879 | 9976237781                | 6104234419      | 37696171       | 0.027605860475         |
| 754880 | 9991752275                | 4908907195      | -3195557       | -0.00227732011875      |
| 754881 | 9997225271                | 6304830846      | 45669535       | 0.03262077115          |
| 754882 | 9986939940                | 3446017336      | -56164178      | -0.038849566596428575  |
| 754883 | 9972883350                | 4046001606      | -33139980      | -0.0238499598625       |
| 754884 | 9988833250                | 4562039638      | -14851010      | -0.010949009045000005  |
| 754885 | 9879423117                | 4135626889      | -28989526      | -0.021609327775        |
| 754886 | 9997141006                | 6334357897      | 43784913       | 0.033358947425         |
| 754887 | 9998893624                | 4928793460      | -2414478       | -0.0017801635099999906 |
| 754888 | 9997482074                | 7978540713      | 100816845      | 0.074463517825         |
| 754889 | 9980251203                | 6621008562      | 58953086       | 0.0405252140375        |
| 754891 | 9998869652                | 5257896581      | 9759317        | 0.006447414525         |
| 754892 | 9954651219                | 4163679272      | -31852080      | -0.02090801819318181   |
| 754893 | 9979424569                | 4422828455      | -21522531      | -0.014429288635714292  |
| 754894 | 9999191875                | 9999191875      | 183728286      | 0.124979796875         |
| 754895 | 9999581144                | 9999581144      | 206706704      | 0.1249895286           |
| 754896 | 9999003447                | 5268978866      | 12510872       | 0.006724471654166675   |
| 754897 | 9982447775                | 7481748019      | 116208456      | 0.062043700475         |
| 754898 | 9997856943                | 6862083577      | 92602264       | 0.04655208941666667    |
| 754899 | 9911087351                | 4676210915      | -16851769      | -0.00809472713499999   |
| 754900 | 9982212109                | 4930648215      | -3580232       | -0.001733794625        |
| 754902 | 9995876655                | 9995876655      | 257461062      | 0.124896916375         |
| 754903 | 9997603542                | 7251069283      | 130497273      | 0.056276732066666675   |
| 754904 | 9962247608                | 6099002154      | 67295935       | 0.02747505385625       |
| 754905 | 9996429183                | 5687878781      | 43278628       | 0.017196969532142854   |
| 754906 | 9998601154                | 5501507472      | 32095492       | 0.0125376868           |
| 754907 | 9997042853                | 9592215526      | 297577501      | 0.11480538815          |
| 754908 | 9998509526                | 8666623123      | 264876337      | 0.091665578075         |
| 754909 | 9996183660                | 3609468634      | -109659761     | -0.034763284140625     |
| 754910 | 9983399167                | 3564081577      | -109302503     | -0.03589796057999999   |
| 754912 | 9999105530                | 8148913565      | 231091557      | 0.0787228391125        |
| 754913 | 9992488695                | 5021238073      | 1681312        | 5.30951834375E-4       |
| 754914 | 9984071165                | 6936074165      | 153350689      | 0.048401854125         |
| 754915 | 9999676041                | 9631050983      | 384566176      | 0.1157762745625        |
| 754916 | 9979786408                | 4846160365      | -14254004      | -0.003845990875        |
| 754917 | 9976566627                | 5666540951      | 61520799       | 0.016663523783333325   |
| 754918 | 9996141781                | 4322179429      | -63604394      | -0.016945514283333324  |
| 754919 | 9988575481                | 6606226291      | 148168776      | 0.04015565728125       |

It's a typical period because base fee changed a lot in this period:

![image](https://user-images.githubusercontent.com/1492263/118216562-547d4a00-b4a6-11eb-99fe-4bf3654cb34b.png)

We can find that `block_gas_limit_undeduped` values across different epochs are almost the same (very close to the max block gas limit: 10_000_000_000), which means, there are always enough messages for miners to package, and miners always package as many messages as they can. `messageRepetitionRate` turns to be the decisive factor of final `block_gas_limit` value.

Here is my problem: how can `messageRepetitionRate` measure network congestion, as the doc says:

> The BaseFee is dynamic, adjusted automatically according to network congestion

**Comment by Kubuxu** [comment]
The delta adjustment formual is a bit different in practice due to tipset system
```
dalta_usage = tipset_gas_limit / N - target_block_gas_limit // corresponds to "block_gas_limit - target_block_gas_limit"
delta_usage = limit(delta_usage, -target_block_gas_limit, target_block_gas_limit)
change = (baseFee*delta_usage) /  target_block_gas_limit / 8
nextBaseFee = baseFee + change
````
where N is number of blocks in a tipset

The primary difference is that we take sum of deduplicated gas limits in the tipsets, not in a block.
It will still depend on packing efficiency (messageRepetitionRate) but not as much.
Every singular block still carries 10B worth of gas in messages, but if there are not enough messages to pack for example 5 blocks in a tipset without major overlaps then the base fee will reduce.

The messages are selected by miners using expected returns calculation based on their "ticket" (256bit VRF randomess), this ticket determines execution order of blocks in a tipset. Miners run calculation of: what is the probability of being 1st, 2nd, Nth to execute messages in the block and depending on these probabilities they select messages with different "profitabilities". This also leads to lower message duplication rates when there are more messages in the mpool.

**Comment by nighca** [comment]
Thx for your reply @Kubuxu, that's quite clear. The number of messages in mpool seems to be the decisive factor.

There is another question I'm not sure about: what decides the number of blocks in a tipset? I can't find the answer in the docs, either.

**Comment by nighca** [comment]
🙆‍♂️
