### ISSUE TITLE
Block reward application needs updating and rethinking

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#126]
We initially had the block reward just be a message from the network actor to the miner. This created an odd special case when validating transactions, and also caused issues with EC transaction grouping (nonce collisions on the message needed an extra special case).

We got rid of all that, and now just directly update the miners balance in the state tree. This is a decent solution, but moving forward we will want to add a constraint that the miner can't spend their block reward funds for some time period. That adds some non-zero complexity.

We should come up with a solution that lets us do this.

One potential idea is to have the miner submit call a 'redeemBlockReward' method on their miner actor, and have this track when each reward becomes spendable. Then later, once spendable, 'withdrawMiningReward' may be called to actually get the funds.

**Comment by decentralion** [comment]
Why do we need the constraint that prevents miners from spending their block reward for some time period? I have a hunch that whatever goal we are aiming for with that mechanism, we could also achieve by adding rules about how the miner can withdraw pledge collateral, and that it will be more convenient to implement it by adding constraints on pledge collateral withdrawal.

cc/ @zixuanzh

**Comment by sternhenri** [comment]
It seems there must be interplay between amount of collateral and block reward (eg block reward can't be higher than collateral, obvs). I understood @whyrusleeping's proposal to be about ensuring that block reward is subject to some of the same withdrawal limits so it can get slashed if abuse is discovered and miners don't run away with ill-gotten gains.

Maybe this can indeed be done away with by designing collateral appropriately (ie taking into account expected reward). Not sure which is better: both are complex in different ways...

Another bad solution here would to be to add block reward to the same holding period as collateral (so presumably it would get slashed as well)... but that seems overly stringent for miners (and a really good incentive to stop mining).

**Comment by decentralion** [comment]
Please take a look at [this design doc][1] on pledge collateral. Our current proposal is that each miner's pledge collateral requirement is a point estimate of their expected block rewards over the coming period `T`, with `T` starting low (e.g. 1 month) during a boostrapping grace period, and then growing to a larger value (eg 12-24 months) in the steady state. 

You point out that "block reward can't be higher than collateral, obviously" which makes me think that we may be missing a constraint in our design--under our current proposal, a miner with very little power will have collateral smaller than a block reward, and if there are O(block reward) sized attacks we need to dissuade, it may be possible to Sibyll away the effectiveness of the collateral. In which case we may want to modify the pledge collateral function to be Expected Reward + 1 Block Reward. (Although this may have the negative effect of greatly increasing mining costs for very small miners.) I'll add a section under the "open questions" section of the design doc so we don't lose track of this.

[1]: https://docs.google.com/document/d/1LJ9z-gmg4CLhuKzD7k9efNAYNNd7HkCGf40PqdMw_-A/edit

**Comment by sternhenri** [comment]
re my "obvs" comment (always a bad word to use, my apologies), I spoke a bit loosely: I meant expected reward.

**Comment by whyrusleeping** [comment]
To clarify: The reason that holding the block reward for some time is desireable is because in the event of a reorg (switching to a different chain) most messages from the chain we are switching from will be in the chain we are switching to, and they will all be replayable. However, if miners are able to immediately spend their block rewards, then in the event of a reorg, those transactions will not be replayable on the new chain. this lands us in a situation where reorgs are a bit scarier than they could be, as there is less certainty on which messages can be reused.

I admit, this isnt *that* good of a line of reasoning, so I'm open to being told that this is a bad idea.

**Comment by sternhenri** [comment]
Understood! Thank you. This may also just be handled off chain (socially) no? As is done with BTC: you have a block confirmation time. Nothing theoretically prevents you from spending your Coinbase early but most folks won’t accept it. 

Maybe this is unnecessary?

**Comment by nicola** [comment]
Current plan: block reward is not locked and can be spent straightaway from miners.

**Comment by sternhenri** [comment]
If that is the plan, it should be pointed out quite vigorously that we recommend FIL clients to nonetheless adhere to a recommended confirmation time. I still agree with @whyrusleeping 's point from above!

**Comment by pooja** [comment]
Okay, addressed the comments above in PR #368
