### ISSUE TITLE
npm notice npm ERR! code 1

### ISSUE THREAD

**Issue by abxd39** [filecoin-project/specs#1265]
$ npm install
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm notice
npm notice New minor version of npm available! 7.19.1 -> 7.20.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.20.1>
npm notice Run `npm install -g npm@7.20.1` to update!
npm notice
npm ERR! code 1
npm ERR! path E:\specs\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\specs\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=E:\specs\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)

**Comment by Stebalien** [comment]
See https://stackoverflow.com/questions/51380209/when-ever-i-run-npm-install-it-fails.
