### ISSUE TITLE
我的FIL出現了Other Penalty是哪裡出錯

### ISSUE THREAD

**Issue by ljh8mg1018** [filecoin-project/specs#1268]
我的FIL出現了Other Penalty是哪裡出錯
![1628733458189](https://user-images.githubusercontent.com/84759516/129129575-03f72aef-f6b8-4ef6-be04-844f4b5d8163.jpg)

下面圖示正常嗎?
![2](https://user-images.githubusercontent.com/84759516/129129697-f017dd87-c7b5-4e1b-8c15-2ac0235e1575.jpg)

求求高手解答

**Comment by Stebalien** [comment]
Please ask on slack https://filecoin.io/slack.
