### ISSUE TITLE
Spec update for FIP-0020

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/specs#1274]
https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0020.md

**Comment by ZenGround0** [comment]
The spec doesn't include any info about the withdraw balance exit code.  That is covered in specs-actors (which is part of the spec) so no work needs to be done to update this value.

**Comment by ZenGround0** [comment]
The code blocks are automatically updated to the new return value because they link directly to specs-actors master branch, so we don't need to change any specs code.  This is a good example of how specs-actors really is "the spec".
