### ISSUE TITLE
i too many init miner... can i remove Owned Miner??

### ISSUE THREAD

**Issue by EJongMoon** [filecoin-project/specs#1289]
![f342](https://user-images.githubusercontent.com/94520036/148255094-d550f1a7-271c-4888-898e-8a2f764b99e6.jpg)

i am learning lotus but made a mistake 
i made an unnecessary miner  so i need help

1. i want remove miner f01667192, f01667659, f01667691, f01669537

2. can i recover the miner f01633154 ?

**Comment by Stebalien** [comment]
Please ask on https://github.com/filecoin-project/lotus/discussions or slack.
