### ISSUE TITLE
Removal of Fuhon network implementation

### ISSUE THREAD

**Issue by kaitlin-beegle** [filecoin-project/specs#1298]
Last week, the Filecoin Foundation formally suspended work on the Fuhon (C++) network implementation.  The existing code repositories will remain public, but shall be unmaintained. 

The updated spec should only make reference to the three actively maintained implementations (Forest, Venus, Lotus), and include a caveat indicating the existence of the C++ repos. It is important that we maintain a record of the existence of these repos, even if there are no current plans to resume work on _any_ C++ implementation.

**Comment by kaitlin-beegle** [comment]
(Also, I believe that opening this issue is the proper protocol, but let me know if you'd prefer I go ahead push changes in a PR!)

**Comment by jenks-guo-filecoin** [comment]
@kaitlin-beegle this is going to be address in [PR #1303](https://github.com/filecoin-project/specs/pull/1303)

**Comment by smagdali** [comment]
Yes, we can republish on specs now!
