### ISSUE TITLE
Note on Bid Orders Expiration

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#13]
Since putting a bid order on the chain deposits the `funds` in the bid order, if the order is never taken the funds will be locked forever, so we need to support an expiry block data for which the order becomes invalid.

This is also useful in case I set a price and given the volatility I dont want that order to be with that particular price forever.

- [x] Need to update spec draft
- [x] Need to update code

**Comment by pooja** [comment]
Bid orders no longer exist, so closing
