### ISSUE TITLE
Discussion: Soft block delay enforcement

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#130]
Even if its susceptible to miners colluding to circumvent it, we should consider adding in block delay enforcement to the protocol. How this roughly works is each miner includes a timestamp in their block, and upon receiving blocks from other miners checks two things:

- the timestamp on the block is not in the future
- the timestamp on the block is at least 30 seconds higher than the latest of its parents

If the received block does not meet both conditions, it should be thrown away.

Pros: 
- Enforces block time as long as miners don't collude and agree to ignore the rule
- Works even without VDFs
Cons:
- Can be circumvented by rational miners who collude and agree to ignore the rule
- Requires miners have very well synchronized clocks

The alternative (or complementary) option is to have a 'good' VDF help enforce the delay.

**Comment by sternhenri** [comment]
We should do this!

**Comment by whyrusleeping** [comment]
@sternhenri yes, we should. Even with a VDF, this provides us decent base level security (especially with a weak vdf that may be broken easily).

Not super applicable here, but heres how bitcoin uses timestamps: https://medium.com/@lopp/bitcoin-timestamp-security-8dcfc3914da6

**Comment by pooja** [comment]
Closed via #191
