### ISSUE TITLE
Filecoin Verify method is mentioned as Todo, is the implementation available for it.

### ISSUE THREAD

**Issue by Swornatoya** [filecoin-project/specs#1305]
When I check the Filecoin Verify method its says Todo. Please tell me if the implementation is available for it.

content/algorithms/crypto/signatures.go

// Verify validates the statement: only `M` could have generated `sig`
--
 
 //    pk - the public key belonging to the signer `M`
 //    m - a series of bytes representing the signed message
 //
 func Verify(pk PublicKey, sig Signature, m Message) (valid bool, err error) {
 panic("TODO")
 }

![image](https://user-images.githubusercontent.com/101313232/197119893-fadba059-f127-4255-a599-c30833159973.png)

**Comment by Stebalien** [comment]
That's more of an abstract definition of "verify the signature on messages". Closest is https://github.com/filecoin-project/lotus/blob/a955a6308a16d80b7f97ff6ef31b278bb20e23c2/lib/sigs/sigs.go#L35-L50.

**Comment by Swornatoya** [comment]
I need to use this Verify, GenPrivate and Sign method in my node.js project. Please let me know if its feasible to use them.
