### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/specs#1321]
#### https://spec.filecoin.io/#section-systems.filecoin_mining.sector
![image](https://user-images.githubusercontent.com/69969590/237052308-2222815a-1a62-4547-abb3-c5200a708c94.png)

----------

#### https://spec.filecoin.io/#section-systems.filecoin_mining.sector.lifecycle
![image](https://user-images.githubusercontent.com/69969590/237055966-4aa18547-bad0-4a1c-bf6e-85c9d334c934.png)

**Comment by ianconsolata** [comment]
These broken links have been fixed, closing.
