### ISSUE TITLE
sector bitfield proposal

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#133]
### Problem
Filecoin miners need a compact way to specify which of a (large) set of sectors is either bad or complete. The number of sectors in the set may be in the tens of millions, and a bitset selecting a subset of them must be much much smaller than that.

If sectors are selected randomly, then it is unlikely that we can gain much over one bit per sector. However, it is very likely that miners will fill disks up one at a time, and so sectors added around the same time would likely be physically near (on the same disk). If a disk failure occurred, then an entire range of sectors would be lost, which is really easy to represent with something like run length encoding. 

## Proposal 0 - Simple RLE
Encode the bitset as follows:

```go
func encodeBitset(bitsetQ) []byte {
  var out []byte
  
  var countType bool
  for !bitsetQ.Empty() {
    var count int
    for bitsetQ.Pop() == countType {
      count++
    }
    out = append(out, varint.Encode(count))
  }
  return out
} 
```

This works pretty well in most ideal cases, but breaks down if bits are set randomly (or in some pattern, like 011011011011). 

## Proposal 1 - RLE + Extension
To address the cases in which the previous proposal is inefficient, we can give the encoding the ability to specify bitfields directly. To do this, we can say that while reading the encoding, if a negative varint is parsed, that many bytes should be read and treated as the exact bitfield for the duration. 

For example:

`000000011111100000011111110110110001010101`
would encode as
`varint<7> varint<6> varint<6> varint<7> varint<-2>[]byte{108, 85}`

(implementation note: it is sufficient just to implement a correct parser for this, and leave the optimization of the encoding up to the individuals)

**Comment by whyrusleeping** [comment]
@dignifiedquire if you wanted to continue with these benchmarks i wouldnt be upset ;)

**Comment by dignifiedquire** [comment]
sounds good, can you give some feedback on the testcases I listed and if you have some others in mind that will come up. Also important for eval is how important are add, remove and merge operations.

**Comment by dignifiedquire** [comment]
Current example numbers.

```
random selection: (200 count)
  raw:     62000 bytes (avg)
  rle:     74724.28 bytes (avg)
  roaring: 49363.02 bytes (avg)
  concise: 128267.32 bytes (avg)
  gz:      27012.03 bytes (avg)
  zlib:    27000.03 bytes (avg)
contingous slices: (200 count)
  raw:     62000 bytes (avg)
  rle:     11.825 bytes (avg)
  roaring: 72.27 bytes (avg)
  concise: 33.92 bytes (avg)
  gz:      113.68 bytes (avg)
  zlib:    101.68 bytes (avg)
```

**Comment by whyrusleeping** [comment]
@dignifiedquire how many random bits are being set in the random selection one? I'd like to see an array of say 100,000ish bits with 100 random bits set, 1000 random bits set, 10,000 random bits set.

Then i'd also like to see the same size of thing with N contiguous runs of 100 sectors, for N={1,2,3,5,10,20}

**Comment by dignifiedquire** [comment]
```
-- Random selections (up to 2%) --
sectors: 3325/10000
  raw:     1250 bytes (avg)
  rle:     4597 bytes (avg)
  roaring: 5674 bytes (avg)
  concise: 10940 bytes (avg)
  gz:      1172 bytes (avg)
  zlib:    1160 bytes (avg)
-- Random selections (up to 5%) --
sectors: 810/10000
  raw:     1250 bytes (avg)
  rle:     1645 bytes (avg)
  roaring: 1602 bytes (avg)
  concise: 2716 bytes (avg)
  gz:      686 bytes (avg)
  zlib:    674 bytes (avg)
-- Random selections (up to 10%) --
sectors: 623/10000
  raw:     1250 bytes (avg)
  rle:     1292 bytes (avg)
  roaring: 1230 bytes (avg)
  concise: 2036 bytes (avg)
  gz:      591 bytes (avg)
  zlib:    579 bytes (avg)
-- Random selections (up to 2%) --
sectors: 44769/100000
  raw:     12500 bytes (avg)
  rle:     51735 bytes (avg)
  roaring: 16408 bytes (avg)
  concise: 146708 bytes (avg)
  gz:      11940 bytes (avg)
  zlib:    11928 bytes (avg)
-- Random selections (up to 5%) --
sectors: 19685/100000
  raw:     12500 bytes (avg)
  rle:     33002 bytes (avg)
  roaring: 16408 bytes (avg)
  concise: 64568 bytes (avg)
  gz:      9335 bytes (avg)
  zlib:    9323 bytes (avg)
-- Random selections (up to 10%) --
sectors: 4627/100000
  raw:     12500 bytes (avg)
  rle:     9699 bytes (avg)
  roaring: 9070 bytes (avg)
  concise: 15072 bytes (avg)
  gz:      4412 bytes (avg)
  zlib:    4400 bytes (avg)
-- Random selections (up to 2%) --
sectors: 425425/1000000
  raw:     125000 bytes (avg)
  rle:     509935 bytes (avg)
  roaring: 131208 bytes (avg)
  concise: 1395636 bytes (avg)
  gz:      117531 bytes (avg)
  zlib:    117519 bytes (avg)
-- Random selections (up to 5%) --
sectors: 148126/1000000
  raw:     125000 bytes (avg)
  rle:     267073 bytes (avg)
  roaring: 127854 bytes (avg)
  concise: 486756 bytes (avg)
  gz:      82695 bytes (avg)
  zlib:    82683 bytes (avg)
-- Random selections (up to 10%) --
sectors: 71275/1000000
  raw:     125000 bytes (avg)
  rle:     143775 bytes (avg)
  roaring: 125278 bytes (avg)
  concise: 233688 bytes (avg)
  gz:      56095 bytes (avg)
  zlib:    56083 bytes (avg)
-- Multiple contigous selections (each up to 3%) --
sectors: 1860/10000
  raw:     1250 bytes (avg)
  rle:     5 bytes (avg)
  roaring: 15 bytes (avg)
  concise: 20 bytes (avg)
  gz:      44 bytes (avg)
  zlib:    32 bytes (avg)
-- Multiple contigous selections (each up to 3%) --
sectors: 7555/10000
  raw:     1250 bytes (avg)
  rle:     9 bytes (avg)
  roaring: 19 bytes (avg)
  concise: 56 bytes (avg)
  gz:      54 bytes (avg)
  zlib:    42 bytes (avg)
-- Multiple contigous selections (each up to 3%) --
sectors: 13639/10000
  raw:     1250 bytes (avg)
  rle:     9 bytes (avg)
  roaring: 19 bytes (avg)
  concise: 88 bytes (avg)
  gz:      54 bytes (avg)
  zlib:    42 bytes (avg)
-- Multiple contigous selections (each up to 3%) --
sectors: 18989/100000
  raw:     12500 bytes (avg)
  rle:     6 bytes (avg)
  roaring: 15 bytes (avg)
  concise: 16 bytes (avg)
  gz:      57 bytes (avg)
  zlib:    45 bytes (avg)
-- Multiple contigous selections (each up to 3%) --
sectors: 139239/100000
  raw:     12500 bytes (avg)
  rle:     11 bytes (avg)
  roaring: 25 bytes (avg)
  concise: 24 bytes (avg)
  gz:      69 bytes (avg)
  zlib:    57 bytes (avg)
-- Multiple contigous selections (each up to 3%) --
sectors: 148036/100000
  raw:     12500 bytes (avg)
  rle:     15 bytes (avg)
  roaring: 33 bytes (avg)
  concise: 60 bytes (avg)
  gz:      75 bytes (avg)
  zlib:    63 bytes (avg)
-- Multiple contigous selections (each up to 3%) --
sectors: 385839/1000000
  raw:     125000 bytes (avg)
  rle:     13 bytes (avg)
  roaring: 103 bytes (avg)
  concise: 32 bytes (avg)
  gz:      179 bytes (avg)
  zlib:    167 bytes (avg)
-- Multiple contigous selections (each up to 3%) --
sectors: 748878/1000000
  raw:     125000 bytes (avg)
  rle:     19 bytes (avg)
  roaring: 188 bytes (avg)
  concise: 48 bytes (avg)
  gz:      186 bytes (avg)
  zlib:    174 bytes (avg)
-- Multiple contigous selections (each up to 3%) --
sectors: 1852476/1000000
  raw:     125000 bytes (avg)
  rle:     6 bytes (avg)
  roaring: 230 bytes (avg)
  concise: 96 bytes (avg)
  gz:      163 bytes (avg)
  zlib:    151 bytes (avg)
```

**Comment by dignifiedquire** [comment]
@whyrusleeping this should give you good overview of things (each section is the average over 10 runs)

**Comment by whyrusleeping** [comment]
@dignifiedquire great results! thank you! which rle is that? the one I described? or something else?

**Comment by dignifiedquire** [comment]
maximum naive rle: https://github.com/filecoin-project/bitsets/blob/master/src/main.rs#L185

**Comment by dignifiedquire** [comment]
I implemented and improved rle, called rle+ which I really like from the characteristics: 

- Results: https://gist.github.com/dignifiedquire/dd05e9d4fd2104b382123277ec3d3a9e
- Format: https://github.com/filecoin-project/bitsets/blob/master/src/main.rs#L222-L231

**Comment by whyrusleeping** [comment]
@dignifiedquire i feel like something must be wrong with the results. The 2% bits set shows rle taking up 3x the space as the data itself? 2% bits set implies an average of 50 empty bits for every set bit, which gives plenty of room to compress via rle.

**Comment by dignifiedquire** [comment]
I agree, this does seem strange. Will investigate further.

**Comment by dignifiedquire** [comment]
Many bugs, little wow in my code. 

Better results are here now: https://gist.github.com/dignifiedquire/2ee6d850105d2706bf1db5ba6091120f

**Comment by dignifiedquire** [comment]
rle+ still looks like a winner on all fronts though

**Comment by dignifiedquire** [comment]
and now in a much nicer format: https://gist.github.com/dignifiedquire/76d98419f003e4015402c810af7ab400

**Comment by whyrusleeping** [comment]
Cool, i'm liking rle+. We should write a decoder and fuzz it a bit, but I think this is good enough for now. We probably want to put a marker in front of the serialized bitmap to serialize the type.

**Comment by dignifiedquire** [comment]
Alright: decoder + tests are up and running: https://github.com/filecoin-project/bitsets/blob/master/src/rleplus.rs

**Comment by dignifiedquire** [comment]
I also wrote a basic spec describing the format here: https://github.com/filecoin-project/bitsets/blob/master/src/rleplus.rs#L1

**Comment by whyrusleeping** [comment]
@dignifiedquire this is great!

**Comment by whyrusleeping** [comment]
Could we copy that specification into a document in this repo, and then also add a prefix marker to the serialized set so that we could hypothetically change it in the future?
