### ISSUE TITLE
How does filecoin reference and encode data?

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#136]
The way we usually reference data in ipfs-land is by the root hash of a graph. Sectors deal in (effectively) flat buffers of data.

Given the hash of a file that is going to be stored, we _could_ just read out into a flat array of bytes, and store that. This provides no overhead (somewhat obviously), but limits the simple storage of data to 'flat files'.

Alternatively, we could store graphs by defining [a format](https://github.com/ipfs/go-car) that serializes a graph into a flat buffer, without losing any information about the underlying graph. This has some overhead over just storing raw data for a file, but allows anyone to easily store any graph they want to in filecoin.

We can also just say that the client should serialize their data in whatever way they want to before sending it to the miner. Which is a great solution. The only drawback here is now we have to define a new protocol for transferring data between clients and miners (if dealing entirely in graphs, we already have a nice protocol for moving graphs of data between peers). The nice thing about bitswap for graph transfers is the very simple resume-ability, an deduplication inherent in the protocol.

We need to decide on exactly how we should be doing this moving forward, as it has significant implications on how interop with IPFS works.

**Comment by whyrusleeping** [comment]
Chatted with @Stebalien about this in person, here are some notes:

# Filecoin Data Encoding
Clients should be able to specify to a miner how the data they are sending is encoded and stored in a sector. They should also be able to specify how the miner should fetch the data.

Some examples (Fc* denotes a filecoin native hash):
A) My data is FcFooBar, You can fetch it from me over **bitswap** by the hash QmFooBar, QmFooBar is a UnixFS file graph with standard filecoin parameters, I want just the leaves packed into the sector.
B) My data is FcBazQwop, You can fetch it from me over **https** at **this url**. I want the data stored exactly as you receive it from there.
C) My data is FcBeepBoop, You can fetch if from me over **bitswap** by the hash QmCats. QmCats is an IPLD graph, and I want every node in the graph stored in the sector using an in order traversal.

In each of these, the client proposes a filecoin native hash, a mechanism for transfer, and a method of encoding the transfer data into the sector. The given filecoin native hash must match the data that is the output of the given encoding method or the miner will reject it.

Now, as far as the storage miner is concerned, that’s all there is to it. But, if the storage miner wants to offer the data they are storing on the retrieval market, they have some options here. 

The base layer, lowest level way of offering data up for retrieval is to let the client request a range of a filecoin native hash (referencing a sector), and returning the specific chunk of the sector that was requested, along with any merkle proof required for the client to verify they are getting what they asked for.

A layer above this can be used to provide better UX to the client in cases where the miner has some knowledge about the structure of the data in the sectors. In this case, the client simply requests an ipfs hash (or selector, pending graphsync) and the miner looks up that object locally and returns it to the client. This is effectively bitswap with payments. The trick here is in how the miner does that lookup. In cases A and C above, the client is giving the miner information about how the data in the sector can be indexed to provide an interface of CID->Sector

**Comment by whyrusleeping** [comment]
Okay, next steps here. We need to define one or more `SerializationMode` values.

I'm thinking that we can just do one for now, and call it `"standard"`. We can then select unixfs import parameters that optimize for point to point file transfer (wider branches, bigger leaves).

I propose that we use 1MB raw leaves with standard chunking, and a max links on intermediate nodes of 1024.

This means that files up to (and including) 1 GB will be just a single root node and its leaves. Files from 1GB to 1TB will have a depth of two. Intermediate nodes will be ~50k maximum size.

Another option is to have 512k chunks, and max width on nodes be 2048. This has the same depth parameters, but has the drawback of doubling the space required for intermediate nodes. The upside for this approach is increased precision and resumeability for transfers. You don't have to transfer an entire megabyte in order to get the 1k of data you might want. Its unclear if this is super useful, and we can always add a new serialization mode later.

**Comment by whyrusleeping** [comment]
This will be done in https://github.com/filecoin-project/specs/pull/242

**Comment by anorth** [comment]
Just to clarify, the "standard" you're proposing corresponds to case A in the previous comment, and not case B, which might be called "raw"?

**Comment by pooja** [comment]
Closable because of @whyrusleeping's PR!
