### ISSUE TITLE
RFC: Open Orders

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#14]
I decided not to include open orders in the current spec

Open Orders are orders that only specify funds and optionally specify time. The idea of these open orders is to be able to set some funds and set the price every X blocks to be the current average price. In this way if someone wants to store the file for one year, they don't have to re-send orders every month because they don't want to predict the future price.

I leave this request for comment open until we figure out all the details about this.

If this doesn't make it into the main spec, it could be an RFC/update to the spec.

---

### Current idea

```
  if b.Price == 0 {
    if b.Time > 0 {
      // Spec: if Time is specified calculate Price from it
      b.Price = b.Funds / (b.Time * b.Size) // TODO check for remainder
    } else {
      // Spec: Pick the average Price of the past 100 deals
      // RFC: How risky is this?
      b.Price = 0 // TODO fix to 10 for now
    }
  }
  // Spec: If the Bid time is not specified, it can be calculated from b.Price
  if b.Time == 0 && b.Price > 0 {
    b.Time = b.Funds / (b.Price * b.Size) // TODO check for remainder
  }
```

**Comment by whyrusleeping** [comment]
This no longer applies, closing
