### ISSUE TITLE
Document block reward decay mechanism

### ISSUE THREAD

**Issue by decentralion** [filecoin-project/specs#147]
I understand that block rewards decay. I would like to know the precise mechanism by which this is computed--does it decay by a tiny amount every block? Or is it recomputed by epochs?

I can't find it in the spec, I looked over the mining doc and every hit in `git grep reward`.

**Comment by whyrusleeping** [comment]
@decentralion we havent yet decided on this. I think the simplest way to do this would be to have it decay in epochs, maybe recalculating once per week or so.

weird side effect of EC: When selecting parents, the more parents you select, the lower your block reward will be (if your block is one that gets retargeted). Its a very miniscule amount lower, but still possibly worth considering.

**Comment by whyrusleeping** [comment]
related work going on in #158

**Comment by whyrusleeping** [comment]
done!
