### ISSUE TITLE
Support for secp256k1

### ISSUE THREAD

**Issue by jesseclay** [filecoin-project/specs#149]
We've chosen to use BLS signatures for the significant benefits they bring -- however this may be a complicated transition for some in the ecosystem to support out of the gate. We should consider supporting a legacy address format off the secp256k1 curve to help facilitate adoption, primarily focused on sending transactions. Initial discussions with @jbenet and @whyrusleeping seem like this may be possible -- but I defer to them.

**Comment by whyrusleeping** [comment]
Yeah, much of the existing crypto infrastructure is annoyingly hardcoded into using secp256k1. We should likely support that in addition to BLS. The increased transaction fees for using secp256k1 will encourage people to update.

**Comment by dignifiedquire** [comment]
For completeness sake, I think it would be great if we could not do that, it would simplify both the code and the protocol. Could we have a list of vendors where this is an actual blocker vs just nice to have?

**Comment by whyrusleeping** [comment]
@dignifiedquire I actually think that this can be done in an elegant way, and doing it right moves us closer towards nice account abstractions.
