### ISSUE TITLE
RFC: Long Deals

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#15]
**Main Question**:
- Can a Storage Miner sign a deal where the `Bid.Time` bigger their available storage `Pledge.Time`?

**Possible Options**:
- **Yes**:
  - They can always plan on renewing their pledge
  - They can always re-sell the storage - or they will lose their collateral otherwise
- **No**:
  - In this way if they want to accept deals, they must commit more storage and put more collateral (which is great!!)
  - They won't be able to plan on re-selling storage by default
  - Great that they cannot overcommit (accept deals that they cannot fulfill completely), hence there is less risk of "re-selling storage", which also means less risk for clients to loose their files.

**Questions**:
- If a Storage Miner does not re-sell on time deal that they could not store (since their `Pledge.Time` is smaller than the `Bid.Time`), how do we penalize them..?

--- 

**My take**: NO (looks like a safe option), YES (if we figure out how to penalize the miners)

**Comment by pooja** [comment]
Already covered in spec
