### ISSUE TITLE
WIP PoSt writeup

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#155]
Posting this as an issue until we can figure out where it belongs, I think it might belong in proofs.md, but i’ll defer to @nicola @sternhenri and @porcuquine 

# Proof of SpaceTime
Proof of SpaceTime is the first of a class of Verifiable Resource Commitment functions. This document provides a brief description of Proof of SpaceTime and the guarantees it provides.

Its interface is as follows:
(data, sk, rb, t) -> (proof)
with
* data: a commitment to the data to be stored over time,
* sk: the prover’s secret key,
* rb: a random beacon to be sampled at regular intervals over time,
* t: a duration for the PoSt,
* proof: a succinct proof of SpaceTime.

A note on rb: we assume the PoSt is provided an adaptive random beacon. That is, a random beacon whose outputs depend on some outside state (that the PoSts can impact). Filecoin currently uses the blockchain as that random beacon.

PoSt proves that over a given proof time, for a particular chain, the prover was correctly storing the data that they claimed to be. A PoSt’s dependence on the particular chain ensures that it is not replayable across different histories (i.e. the resource was committed to a given history of the blockchain).

This builds upon another Verifiable Resource Commitment function, the Proof of Replication, by not only proving that a given replica was stored at a given point in time, but that it was stored continually over a time period.

An attacker attempting to not store all of the data, or store incorrect data can not store (or fake) X% of data, and be caught with high probability (X is tunable).

In particular, PoSTs have the following guarantees:
* a PoSt may not be computed in less than the expected time,
* it also may not be computed for some period of time in the past any faster than it was initially computed,
* a PoSt generated for a particular history is not valid for a different history.

The data being proved may be very large (petabytes, exabytes) without changing the security guarantees.

Additionally, PoSt guarantees that an attacker cannot contract themselves to store data that they can generate with some known function. Specifically, an attacker A has a function F to generate some data. They contract themselves to store this data, and then don’t actually store the data. When challenged, they use the function to regenerate the data on the fly and respond to challenges.

We prevent this by requiring a slow setup step for each piece of data included in the set. In order to complete the PoSt, the output of the ‘setup’ phase is needed. If an attacker were to attempt to compute this on the fly, their PoSt submission would be tardy and they would be caught.

**Comment by pooja** [comment]
@whyrusleeping Please PR

**Comment by pooja** [comment]
@whyrusleeping Talk to nico about a path forward

**Comment by mishmosh** [comment]
Closing this issue since PoSt design has moved forward: https://filecoin-project.github.io/specs/#algorithms__post
