### ISSUE TITLE
Spec clarification: make it clear that power is reduced when stopping prove data

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#156]
The spec mentions in a small line [here](
https://github.com/filecoin-project/specs/blob/master/storage-market.md) “Power is deducted when miners remove sectors by reporting the sector 'missing' or 'done' in a PoSt.”

This needs a tiny bit more of explanation like: Only proved storage is counted towards power. As long as the miner keeps on storing the data and proving it (even if the deal is expired), the data counts towards power. The miner can stop proving data by reporting it in the missing or done, and the power is removed.

**Comment by whyrusleeping** [comment]
Power adjustments happen during submit post, please review the psedocode i wrote here: https://github.com/filecoin-project/specs/blob/master/actors.md#submitpost

**Comment by nicola** [comment]
While this explicitly says how it works (which is great!), I think my original comment is that in the rest of the spec, we should make it clear that this is the case (instead of having readers to go in an actor doc and read some code).

**Comment by pooja** [comment]
@nicola Does this still need to be addressed? If so, want to take a stab at it?

**Comment by whyrusleeping** [comment]
@nicola PRs are accepted, please contribute wording that satisfies your requirements.

**Comment by pooja** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spec clarification: make it clear that power is reduced when stopping prove data](https://trello.com/c/CRstIOU2/64-spec-clarification-make-it-clear-that-power-is-reduced-when-stopping-prove-data)
