### ISSUE TITLE
Initial investor accounts

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#157]
The filecoin network has a set of initial investors whose accounts will be created and seeded in the genesis block. These accounts will contain the full balance, but be timelocked, so that funds may be withdrawn from them over time. The exact setup of these accounts needs to be thought through.

Some considerations:
- One account per person may deanonymize people who wish to remain more pseudonymous. Splitting all accounts into N accounts of equal balance may help here.
- Some people may with to have multisigs set up
- Some people may wish to have another party manage their funds for them

@jesseclay has volunteered to do some additional thinking and exploration here.

**Comment by jesseclay** [comment]
@whyrusleeping  -- had a chat with @ianjdarrow and @protocolin on this -- I'll come up with an initial scoping/requirements doc to start hashing out all the concerns here and pushing this workstream forward. I expect that doc to be mostly complete by end of next week - will loop you & whoever else is interested into it.

**Comment by pooja** [comment]
@jesseclay Do you have an update on this? Thanks!

**Comment by jesseclay** [comment]
PR here: https://github.com/filecoin-project/specs/pull/416

Thanks!

**Comment by jesseclay** [comment]
#416 merged awhile back. Closing this out.
