### ISSUE TITLE
Block reward calculation

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#158]
computing what the reward for a given block should be is trickier than it seems at first. We have two constraints. After infinite time, 1,400,000,000 Filecoin will be issued, also, the block reward at point X in time should be twice the reward at point X + (6 years).

This leads to a fairly complicated equation of the form `V*2^(-x/S)` for the instantaneous block reward. Taking the integral of that gives the total block rewards issued at some point in time. Solving for the root of the integral allows us to shift the starting point of the graph, and that solution involves some logarithms. 

A complicating factor for filecoin is that at each round, we have zero, one or multiple blocks, so the number of blocks released at a given point in time is variable. In order to ensure that we release *exactly* 1.4B filecoin, retargeting is required. This retargeting is complicated to do.

An alternate method for expressing the block reward is to solve for an initial block reward value, then shrink it at each step in such a way that its halved over six years. This method works, but retargeting seems equally as difficult, and the method as a whole seems a bit more error prone (rounding errors multiply). That said, its a much simpler equation (if just an approximation).

I've worked up the first of these options in this observable: https://observablehq.com/d/e1fdc5a75843b74d

An option that potentially simplifies things (a little bit) is to do block reward adjustment every fixed time period. Having the block reward remain fixed over a given time period, and adjusting it every week (for example).

**Comment by whyrusleeping** [comment]
#126 is related

**Comment by decentralion** [comment]
I have a question about the requirements, @whyrusleeping. The targeted block decay is documented in years, but unless I'm mistaken, the protocol doesn't actually contain a clock. So we're actually going to have to express the equations in terms of number of rounds, based on our a-priori estimate of the relationship between # of years and # of rounds.

Do we plan any re-targetting mechanism if there's temporal drift? E.g. blocks get produced 2x faster than expected (VDF breakage?). Are there robust mechanisms that prevent such drift from occurring?

I'm guessing the answer is something like "fixing temporal drift would require a time oracle that we don't have, so a hard fork, so it's possible but would only happen if it got really bad". 

Anyway, given that we don't have access to time, I assume we need to translate 6 years into rounds upfront. Can you provide / link to the relevant equation?

**Comment by whyrusleeping** [comment]
Yeah, 6 years is 6*365*24*60*2 rounds, which is conveniently near 6 million.

**Comment by whyrusleeping** [comment]
Actually, a thing that makes this all much easier is that we're never actually 'minting' any filecoin. All filecoin that exists is present at network launch, the block reward is just transferring funds from the networks account to the miners. In this way, we can easily avoid putting out too much. I'm less worried about this now.

**Comment by decentralion** [comment]
I have an intuition that we can compute the block reward as "some fraction `r` of the remaining filecoin in the genesis account", with `r` computed based on the round number. This sort of gets "perpetual automatic retargetting"
