### ISSUE TITLE
Refactor Signature Spec

### ISSUE THREAD

**Issue by bvohaska** [filecoin-project/specs#164]
The Address and Signature specs conflict due to the recent changes to the Address spec. Work will need to be done to bring the Signature spec into alignment.

**Comment by whyrusleeping** [comment]
I don't think they are yet in conflict. We still do signatures the same way. However, we will need to change how signatures work soon in order to allow different types of signatures. This should probably be done soon.

**Comment by bvohaska** [comment]
Moved issue content [here](https://github.com/filecoin-project/specs/issues/123)
