### ISSUE TITLE
Actor ID Issuance

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#170]
The current thinking for allocating actor IDs is to track them in an actor (the init actor, ref #169 ). This is really nice as it keeps all 'state' in the state tree, and everything is just done through actors.

However, theres a bit of funkyness here. Doing things this way means that two messages that create actors, but otherwise have no interactions with eachother, will now execute differently if reordered. This creates a bit of weirdness for our future selves who want to think about executing messages in parallel.

An alternative proposal would be to not track actor IDs in the state tree, or even assign them during actor creation, but instead track all actors created during the process of executing a block, then at the end, allocate IDs for all the new actors all at once. This ends up with the same result, but possibly easier to reason about the execution of different messages interacting with eachother.

cc @dignifiedquire @frrist

**Comment by dignifiedquire** [comment]
Given that they do interact with the init actor they do depend on a shared resorce, so will likely need to do some locking on that in a parallel context even if the id assignment is pulled out. So I don’t think that would be good to special case, as it complicates things, for possibly no real benefit in the future.

**Comment by dignifiedquire** [comment]
@pooja could you say why this was closed, unclear to me what the resolution here is.

**Comment by pooja** [comment]
@whyrusleeping Could you chime in here? @dignifiedquire I closed at why's request, but don't know the exact details you're probably looking for.
