### ISSUE TITLE
Investigate https://github.com/tabatkins/bikeshed/

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/specs#173]
Example rendering of the Address spec https://gateway.ipfs.io/ipfs/QmeHfZQgH2kztr4d4EgiHcFATGDVyE6z1tEu5nPcGpmbE4#protocol-3-bls

**Comment by whyrusleeping** [comment]
looks pretty nice. Thats a better rendering than gitbook IMO

**Comment by dignifiedquire** [comment]
There is not much change needs to happen to using it

- rename `.md` -> `.bs` 
- add some small frontmatter describing the spec to each file 
- fix headings (they need to be "proper" in the sense h2 after h1 etc)
- profit

**Comment by whyrusleeping** [comment]
@dignifiedquire sounds like that could be a compile step, no?

**Comment by dignifiedquire** [comment]
we now have our own solution using hugo
