### ISSUE TITLE
The diagrams issue

### ISSUE THREAD

**Issue by mhammersley** [filecoin-project/specs#174]
Diagrams/illustrations will improve understanding of the spec; this issue should serve as the running list for all of them.
@dignifiedquire pointed to this tool as being particularly easy for creating diagrams (flow diagrams in particular): https://mermaidjs.github.io/sequenceDiagram.html

- [ ] state machine diagram for actors.md
- [ ] things that are on-chain vs things that are off-chain (related to storage-market.md)
- [ ] ticket chain growth and sampling as part of expected consensus
- [ ] slashing condition visualizations

**Comment by bvohaska** [comment]
@meiqimichelle for awareness

**Comment by sternhenri** [comment]
All tied to EC:
- [ ] Diagram for min ticket selection from Tipsets
- [ ] Diagram for tie breaking for Tipsets of equal weight (on different forks) iterating through tickets to find min
- [ ] Diagram for ticket production per round vs block production

**Comment by meiqimichelle** [comment]
Curious if you ended up trying Mermaid and have feels -- thinking about using it for some Cluster diagrams (well, the ones that need to be easily updated on a regular basis).

**Comment by sternhenri** [comment]
I did not alas :/
