### ISSUE TITLE
Trusted setup ceremony planning

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#177]
Writing this issue here in specs, though maybe it could be moved to rust-proofs (I saw it as a broader protocol concern than just the rust-proofs lib).

We need to start planning for the trusted setup ceremony. This MPC will be a pretty significant endeavor, and is very much non-trivial. It will be hard, and getting it right is critical.

We should be able to use the same software that Zcash used for their latest ceremony, and I’m so happy that they paved the way here (Thanks @zookozcash and team :). That said, We have a few complicating factors. Their ceremony was for a single circuit, we have many, and on top of that, our circuits are *very* large. 

I don’t have any solutions here, but I just wanted to start a discussion.

Some potential talking points:
- Bandwidth requirements for participants in the ceremony
- Splitting up the ceremony into smaller ceremonies
- How big does the ‘power of tau’ equivalent need to be?
- What is our threat model for the ceremony?

Some things not to discuss here:
- Details around how the ceremony might be run. A fair amount of security here is gained through secrecy. So don’t go talking about your plans to go run the ceremony from the top of mt Tam.

cc @porcuquine @nicola @pooja @jbenet (and feel free to tag others)

**Comment by porcuquine** [comment]
@sanchopansa @stefandeml

**Comment by whyrusleeping** [comment]
Also included in the setup is the DRG generation, which is just picking a good random seed number, but still something to be considered.

**Comment by mishmosh** [comment]
Trusted setup is now underway. @jnthnvctr can you review, and close if this issue is no longer needed?
