### ISSUE TITLE
[tickets] Tie breaking the tie breaker

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/specs#185]
Per discussion with @ZenGround0 we should quickly make an additional condition on how miners should tie break in case both chain weights are equal and min tickets are the same. 

Given the very nature of the min tickets this is extraordinarily unlikely to happen (like really really unlikely: uniformly drawing two n bit strings, chance of a collision is 1/(2^n) with n >= 256... i.e. negligible) but it'd be nice for this to be specc'd anyways, for completeness' sake... Maybe we can just look at the next biggest ticket in the tipset and use that as the tie breaker...

If you agree @whyrusleeping I can make a quick PR

**Comment by sternhenri** [comment]
As @whyrusleeping suggests, this would mean we've found a collision to sha-256 or something, so more importantly, it would be 
> if equalTickets { worldPanic(); }

but will either link to a PR in coming days or close

**Comment by ZenGround0** [comment]
I think there might be a situation where this actually occurs with high probability.

There are two tipsets being compared with the same weight
* T1 consists of block A and B, min ticket b from block B
* T2 consists of block C and B, min ticket b from block B

In the big picture any miner that sees these two tipsets would combine them into tipset T3 with blocks A, B, C.  In fact in the go-filecoin code right now I believe we always do this combination first so we never hit the comparison case.  That seems like it might be an implementation detail though.  

Seems wrong to panic if your node compares T1 and T2 and seems wrong to mix EC chain selection rules with process of searching through all possible tipsets to make sure that no node ever compares T1 and T2.  Currently the code mixes these abstractions which is not great and probably shouldn't be enshrined in the spec.

Maybe compare next highest ticket until we find one that is different?

**Comment by sternhenri** [comment]
V good points @ZenGround0! Agreed with your proposed approach. Will PR it and link here.

**Comment by sternhenri** [comment]
review please: https://github.com/filecoin-project/specs/pull/190

**Comment by pooja** [comment]
Closed via #190
