### ISSUE TITLE
Use protocol versions during sync

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#198]
Once we have the block height to protocol version mapping in the spec (#197) the syncing protocol should be upgraded so that syncing blocks of a given height is done with respect to the protocol version that is in scope for that block's height.

**Comment by anorth** [comment]
I'm not sure we need anything in the spec for this.

**Comment by mishmosh** [comment]
Closing for now, feel free to reopen if you feel this is still required.
