### ISSUE TITLE
Decide on including a starting block height in a deal proposal

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#200]
Ripping this text directly from a TODO in `network-protocols.md`

Possibly also include a starting block height here [the deal proposal], to indicate when this deal may be started (implying you could select a value in the future). After the first response, both parties will have signed agreeing that the deal started at that point. This could possibly be used to challenge either party in the event of a stall. This starting block height also gives the miner time to seal and post the commitment on chain. Otherwise a weird condition exists where a client could immediately slash a miner for not having their data stored.

Filing this issue to track all work needed to close out this TODO, either by deciding to drop this idea and remove the TODO, or write up this idea and officially get it into the spec.

**Comment by mhammersley** [comment]
@nicola , is this faults related?

**Comment by mhammersley** [comment]
also @sternhenri for awareness

**Comment by sternhenri** [comment]
I think @whyrusleeping is decider here. What's the current consensus here, do we still believe this is necessary @whyrusleeping ? If so, can you spec it real quick and merge? Also happy to do it if you can discuss for 5 mins.

**Comment by mishmosh** [comment]
This is done.
