### ISSUE TITLE
Decide on adding a data transfer protocol specification to the storage deal protocol

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#201]
From a TODO in `network-protocols.md` preceding `miner.RegisterInboundFileTransfer(resp)` with the `HandleStorageDealProposal` pseudocode:

"potentially add in something to the protocol to allow clients to signal how the file will be transferred"

I believe this is related to the often brought up idea of allowing for clients to ship miners hard drives.

**Comment by mishmosh** [comment]
Done: https://filecoin-project.github.io/specs/#systems__filecoin_files__data_transfer
