### ISSUE TITLE
Consider usage of types: attofil vs integer in spec

### ISSUE THREAD

**Issue by mhammersley** [filecoin-project/specs#203]
@whyrusleeping , @dignifiedquire  
Per spec review conversation on specs #131

**Comment by whyrusleeping** [comment]
It likely makes sense here to explicitly say which fields are ‘currency units’ and not just regular integers. Even though they will likely be handled exactly the same under the hood, it may be helpful to implementations to distinguish these types

**Comment by dignifiedquire** [comment]
will be fixed with #352
