### ISSUE TITLE
Consider using compact serialization instead of CBOR RPC

### ISSUE THREAD

**Issue by mhammersley** [filecoin-project/specs#204]
@whyrusleeping , @dignifiedquire
Per Mar 19 2019 spec review conversation on network-protocols.md

**Comment by whyrusleeping** [comment]
Question to answer here: For our network protocols, should we use the Filecoin Compact Serialization instead of the CBOR RPC?

**Comment by pooja** [comment]
@whyrusleeping Please respond and close!

**Comment by whyrusleeping** [comment]
@dignifiedquire if we do that then we have to define FCS types for each of the types in each of the network protocols. which kinda sucks.

Additionally, I think that its probably a good thing to have the data sent in RPC type protocols be a little more verbose and human readable.

**Comment by dignifiedquire** [comment]
> we have to define FCS types for each of the types in each of the network protocols

I don't think that is actually that much work, given there are not that many distinct types at is pretty straightforward how to derive FCS for a new type, but I accept that this is a drawback.

> be a little more verbose and human readable

why?

-- 

How about we use just CBOR, but not as FCS, so we can drop the length prefixes, but rather wrap things in CBOR arrays, or even just a stream of CBOR objects, as they already describe their own length in a deterministic way.

**Comment by whyrusleeping** [comment]
(@dignifiedquire and I chatted about this)

The idea in the previous comment amounts to dropping the bytes length prefix on CBOR-RPC, which is fine because cbor objects are self terminating anyways. I think this is a pretty reasonable thing to do.

**Comment by dignifiedquire** [comment]
was this written into the spec?

**Comment by pooja** [comment]
I don't think so. @whyrusleeping mentioned that this was something that doesn't require spec changes yet, but can you confirm why? @dignifiedquire if you think this needs to be written into the spec, would be great if you took lead on that!

**Comment by dignifiedquire** [comment]
The last state described here does require changes in the spec if we want to do it

**Comment by pooja** [comment]
Okay @dignifiedquire. Want to take it on?

**Comment by pooja** [comment]
Okay @dignifiedquire. Want to take it on?
