### ISSUE TITLE
Evaluate order of cids in parent field

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#206]
Should there be a canonical order?  If so what should it be?  Right now we lexographically order by cid, it may also make sense to order parent cids by the lexographic order of their tickets.

**Comment by whyrusleeping** [comment]
The tradeoff here is between making finding the smallest ticket parent of a block easier, and making sorting a set of parent cids easier.

Thinking about it some more, I think that keeping the bytewise lexicographic sort of the Cids is probably the right thing to do, as the added complexity required in the alternative is pretty annoying, and we really don't gain *too* much by sorting by ticket order.

Let's keep things as is :)
