### ISSUE TITLE
Is Replication Factor for data defunct?

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#209]
A while back I remember discussion of PoRep being useful for guaranteeing multiple physical copies of the same data.  IIRC there was discussion of a client specifying a replication factor as part of negotiating a storage deal with a miner.  Looking at the storage deal proposal I don't see any mention of replication factor.  Was there a decision to move away from the single deal / many replicas workflow?

**Comment by whyrusleeping** [comment]
@ZenGround0 The replication factor is a clientside thing that determines how the data is split up locally, and how many different miners they reach out to. For example, for a 3x replication, you would contact three different miners and store your data with them.
