### ISSUE TITLE
MessageReceipt has two versions  in Data Structures

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/specs#215]
In the [data structures spec](https://github.com/filecoin-project/specs/blob/master/data-structures.md), MessageReceipt is shown twice, and there are differences:  One has `Return [][]byte` and the other has `Return []byte`

**Comment by whyrusleeping** [comment]
Oh weird, must have been a merge conflict that made it in without getting noticed. Will address.

**Comment by whyrusleeping** [comment]
closed in #216
