### ISSUE TITLE
Getting concrete about chain selection in spec

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#220]
This comment from @phritz: https://github.com/filecoin-project/go-filecoin/pull/2425#issuecomment-479178861 is worth reading.

The gist of this comment is that it is non-trivial to implement chain selection in such a way that it ALWAYS selects the heaviest chain because tipset rules mean that new blocks might validly be merged with existing blocks to create a heaviest tipset.  The `widen` function in the existing implementation is currently just an implementation detail but the above comment makes a strong case for speccing out something like it explicitly to aid in development.

Unclear where this belongs, likely candidates are chain syncing and EC spec.

**Comment by mhammersley** [comment]
@sternhenri for awareness

**Comment by sternhenri** [comment]
This is a key point @ZenGround0, thanks for raising (and sorry for lag). Has it been addressed to your liking in the current v of the spec? My sense is no, but the choice (per https://github.com/filecoin-project/specs/pull/295) was to leave some of this up to the implementer: ultimately no implementation can "ALWAYS" select the heaviest chain.

I understand this to be equivalently problematic to how long a miner waits before starting to mine (lest a min ticket come in later). Mistakes in either case leads to foregone potential returns. With that said, given that I am not sure there is a "right" solution, I'm tempted to leave this up to the implementer but am happy to try and define a default if helpful...

**Comment by mishmosh** [comment]
EC has been overhauled in descriptions of heaviest chain so closing. If you still feel this isn't sufficient, please reopen.
