### ISSUE TITLE
Is this feasible that a go-filecoin node can specify multiple directories?

### ISSUE THREAD

**Issue by waynewyang** [filecoin-project/specs#257]
- Go-filecoin can only specify one directory,  I think it will result that it's hard to manage multiple hard disks, IPFS has the same question I think. 
    - one hand, it is wasting space if using RAID , it does't match  filecoin's vision, because we need lower  costs.
    - on the other hand, LVM is not safe, All disks can't work if one disk does't  work.

So  I think about that if IPFS and go-filecoin can specify multiple directorys? or everyone else has good idea?

**Comment by anorth** [comment]
Hi @waynewyang, could you please re-open this issue on the `go-filecoin` repository instead? It's an implementation concern more than protocol specification. I'll respond in more detail there.
