### ISSUE TITLE
Auto deploy specs

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/specs#264]
Should be pretty straightforward with github actions: https://github.com/benmatselby/hugo-deploy-gh-pages

**Comment by pooja** [comment]
@mslipper This is related to #266. Any interest in taking this as well?

**Comment by jimmylee** [comment]
I'm taking this task as discussed with @mishmosh.

**Comment by jimmylee** [comment]
PR is live here: https://github.com/filecoin-project/specs/pull/884

+ need to resolve: `cannot find module providing package crypto/ed25519`
+ need to test `make publish`

**Comment by jimmylee** [comment]
Solution is merged! Thanks everyone.
