### ISSUE TITLE
How to Mining Blocks

### ISSUE THREAD

**Issue by no1lcy** [filecoin-project/specs#265]
My system is CentOS 7.3, mine ID is  t2fzjpld4qcmxi2xl67maenqieoh5bohl6x4or2yi。Proven storage has been realized and displayed on the website（https://stats.kittyhawk.wtf/storage/mining）, but it has not been blocked since the command start mining. Is there any operation missing?

**Comment by whyrusleeping** [comment]
Hey @no1lcy, this is the repo for the Filecoin Specification. Issues related to implementations should not go here. Please post this over on https://discuss.filecoin.io/

Thanks for trying things out :)

**Comment by no1lcy** [comment]
> Hey @no1lcy, this is the repo for the Filecoin Specification. Issues related to implementations should not go here. Please post this over on https://discuss.filecoin.io/
> 
> Thanks for trying things out :)

thanks!
