### ISSUE TITLE
hugo menu structure doesn't indent properly

### ISSUE THREAD

**Issue by gnunicorn** [filecoin-project/specs#271]
address, signature and alike are supposed to be within/under/in "cryptography" (which isn't actually a link) and are written like that in the markdown file, but hugo renders it wrong, making it a two-level-flat menu:

![Screenshot-20190514124241-684x1442](https://user-images.githubusercontent.com/40496/57692046-109ca380-7646-11e9-9d79-91416a31f3ac.png)

**Comment by dignifiedquire** [comment]
I think we should restructure the content to avoid nesting deeper, more than one indentation in the main navigation will make it hard to grasp things.

**Comment by gnunicorn** [comment]
I generally agree we should keep it as flat as possible. But three layers of depth aren't really that much for a specification - and the current highest layer isn't even actual docs but more ... dividers of main sectors.

**Comment by dignifiedquire** [comment]
I think that works, maybe we could reduce the font-size a little bit for the 3 level

**Comment by gnunicorn** [comment]
will send a PR later

**Comment by dignifiedquire** [comment]
thank you
