### ISSUE TITLE
SubmitPoSt psuedocode represents "recovered" and "done" as "BitField", but docs use "SectorSet" type

### ISSUE THREAD

**Issue by laser** [filecoin-project/specs#276]
The [SubmitPoSt](https://github.com/filecoin-project/specs/blob/master/actors.md#submitpost) portion of the specs lists the method's parameter names and types:

```
Parameters:
    proofs []PoStProof
    faults []FailureSet
    recovered SectorSet
    done SectorSet
```

However, the pseudocode uses different types:

```
func SubmitPost(proofs []PoStProof, faults []FaultSet, recovered BitField, done BitField) {
```

Both [`BitField`](https://github.com/filecoin-project/specs/blob/master/data-structures.md#bitfield) and [`SectorSet`](https://github.com/filecoin-project/specs/blob/master/data-structures.md#sectorset) exist in our Data Structures spec - so it's not clear to me which of the two types we should use.

Should the `SubmitPoSt` method accept `BitField` or `SectorSet` for `recovered` and `done`?

**Comment by ZenGround0** [comment]
Looking over related issues it is becoming increasingly clear that these params should be bitfields.  I'm going to speculatively submit a patch.

**Comment by pooja** [comment]
cc @dignifiedquire (for its relevance to PR #251 )

Need to clarify that FailureSet is an array of Bitfields, faults recovered and done use RLE bitfields

**Comment by dignifiedquire** [comment]
they are bitfields in `master` now
