### ISSUE TITLE
storage deal protocol should have way of negotiating transfer mechanism 

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#283]
As pointed out by @gnunicorn on slack:

> ...around `accepted` it explains that transfers happen out of band of this, but the protocols doesn't even facilitate the negotiation through which protocol that should happen . Maybe we want to add a field in the proposal about the different means the transfer can happen? Like, if you want to sent a hard-drive (as suggested) but the system is automatic and only accepts bitswap, then it shouldn't have accepted the deal to begin with no? And maybe in the accept we also want to supply some connectivity information already so that this can happen automatically and timeouts within which that must have happened otherwise the deal is off (if the proposed protocols supports that)?

**Comment by anorth** [comment]
I think this is the same as #201

**Comment by pooja** [comment]
Closing in favor of #201
