### ISSUE TITLE
Define ordering of parent CIDs in block header

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#285]
Blocks in a tipset are to be ordered by ticket. Define the order of parent CIDs in Block header to match this. Note that this requires access to the parent blocks in order to validate ordering.

A possible extension is to relax the tipset concept to only require blocks in a tipset to have matching sets of parent CIDs, ignoring ordering. The ordering of parents in a block header could then be intentionally undefined.

Slack [thread](https://filecoinproject.slack.com/archives/CHMNDCK9P/p1558433081202800).

I intend to update the spec in concert with implementation. cc @whyrusleeping @gnunicorn

**Comment by anorth** [comment]
Doing the implementation has finessed my understanding here. My original proposal to order the parents by ticket is still possible, but I'm no longer sure it's the best way.

Logically, we want to consider two tipsets (collections of blocks) equivalent if they have the same blocks, without reference to ordering, because code processing the tipset will always order them by ticket. Multiple places need a "key" by which to refer to a tipset, the block header parents being one, and datastores being another. It is desirable that the keys for two equivalent tipsets compare equal, i.e. without regard to ordering, without reference to the blocks to which they refer. That means the order of the cids in an array serialization of a tipset key must be ignored. Checking for ticket-ordering at deserialization-time is too awkward.

Two ways of doing that are:
- just define the semantics of block.parents as a set, order irrelevant, leave implementations to decide how to realise that (@gnunicorn 's suggestion)
- define a canonical serialization in sorted order (the current go-filecoin code)

Both have the downside that the ordering of block cids in block.parents may not correspond to the order in which they are processed. I think we just have to live with that.

So I'm fine with either of the alternatives, open to @whyrusleeping to make the call. In go-filecoin I think we'll implement the tipset key as a sorted set anyway, but if we take the first path, it won't be a "syntax" error when deserializing if they're not sorted.

**Comment by whyrusleeping** [comment]
I think its probably best to not specify an ordering at all. It's a little annoying, but i think having the ordering be different from the state application ordering is more annoying, and having to pull out all the extra information necessary to sort them by ticket is especially more annoying.
