### ISSUE TITLE
Hugo-generated documentation site breaks all links

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#291]
I think all the links in the hugo-generated site are broken. For example, see the links at the top of https://filecoin-project.github.io/specs/docs/expected-consensus/

A relative link like `faults.md` or `./faults.md` is broken because the page name appears as a path with a trailing `/`. Similarly an absolute ref like `/faults.md` is broken by the `/specs/docs/` path prefix. There may be a syntax that works, and is also compatible with raw markdown viewers like GitHub, but I haven't found it yet.

**Comment by pooja** [comment]
cc @mslipper @dignifiedquire

**Comment by mishmosh** [comment]
New generation process, so this is obsolete.
