### ISSUE TITLE
Spec for late/failed PoST fees, robust payment mechanism

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#293]
The [miner actor](https://github.com/filecoin-project/specs/blob/master/actors.md#submitpost) `SubmitPoSt` invokes `ComputeLateFee` to compute fees for late submission of a proof, but that method is currently unspecified. See also https://github.com/filecoin-project/specs/blob/master/faults.md (which calls it `CalculateLatePenalty`).

1. The call site implies that the late fee is a pure function of the number of blocks late that the submission is. Should it not also be a function of the miner's pledge collateral or committed bytes?
1. The faults spec implies that the late fee included in the message must exactly match the computed fee. Since it's a function of block height, this will be a brittle check, prone to failing due to propagation delays or censorship, adding yet more fee burden. I propose that this should be made more robust. Two suggestions are:
    1. the message may carry more than the required fee, and the balance is refunded to the offender when the message is processed
    1. the message may carry less than the required fee and still be accepted; the miner remains in an under-collateralised state (which can occur for other non-malicious reasons too)

[Late PoSts might *still* suffer from censorship, but let's not bury this issue in that discussion]

Go-filecoin is implementing this soon. The specific function arithmetic may be changed later, but it would be helpful to be confident in what the parameters to the late fee function are, and the requirements for the network accepting it.

**Comment by ZenGround0** [comment]
3. We also need a spec for the related `ComputeTemporarySectorFailureFee` during Reported Storage Fault Penalties.  As for `ComputeLateFee` the exact arithmetic isn't so important but the interface is.  Also this fee seems to not depend on block time so payment does not suffer from the issue described in bullet (2)

**Comment by whyrusleeping** [comment]
> The faults spec implies that the late fee included in the message must exactly match the computed fee.

It doesnt.

> the message may carry more than the required fee, and the balance is refunded to the offender when the message is processed

yep! It does this, see the code for submitPoSt:
```go
	if msg.Value < feesRequired {
		Fatal("not enough funds to pay post submission fees")
	}

	// we want to ensure that the miner can submit more fees than required, just in case
	if msg.Value > feesRequired {
		Refund(msg.Value - feesRequired)
	}
```

I'll work on a PR for the parameters for the late fee functions.

**Comment by whyrusleeping** [comment]
@anorth does #312 address this for you? we should make new issues for the specific constructions of those fees, but this gets things in the right shape

**Comment by anorth** [comment]
Thanks. The PR fixes the late fee computation call in `faults.md` to which I was referring. I think this bit is good for implementation now.
