### ISSUE TITLE
Specify burn mechanism

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#296]
The `BurnFunds` method called by `SubmitPoSt` is not specified.  I recently heard that burning sends funds to a special address where they are locked up until the day a protocol upgrade allows withdrawing these funds for other protocol purposes.  Burning could also just erase an actor's funds.  Either way the mechanism needs to be written in the spec.

**Comment by whyrusleeping** [comment]
this should be addressed now: https://github.com/filecoin-project/specs/blob/master/state-machine.md#burning-funds
