### ISSUE TITLE
Address TODOs in faults.md

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#297]
Here are remainingTODOs in faults.md:

* Under the Penalization section of Reported Storage Fault Penalties: Should the collateral lost be proportional to the remaining time?
* Under the Penalization section of Reported Storage Fault Penalties: (addressed to @nicola) Check if the time between  posting two proofs allows for a generation attack if it does not then we might reconsider the sector not being lost
* Exact parameters for PoSt Deadline and Gen Attack threshold (not critical for implementation at this time)

**Comment by whyrusleeping** [comment]
@nicola can you take a look at these TODOs?

**Comment by mhammersley** [comment]
@nicola , is this something we might want to address at the research week?

**Comment by dignifiedquire** [comment]
Will be fixed as part of #374
