### ISSUE TITLE
Miscellaneous Miner Actor Spec Improvements

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#299]
The go-filecoin team pointed out these areas in the miner actor's contracts as needing work to facilitate a complete implementation.

- [ ] At some point we need to specify `CollateralForSector` as called by [CommitSector](https://github.com/filecoin-project/specs/blob/master/actors.md#commitsector).  Including how it differs based on pledge amount and sector size.
- [x] The worker / owner distinction makes sense but it is not specified enough to be easily understood or implemented.  
  - Motivation behind worker account in the comments above the field in the miner actor would resolve lots of confusion
  - The worker is not specified [during construction](https://github.com/filecoin-project/specs/blob/master/actors.md#constructor) and I can't find a setting method.  Right now there is now way to assign a worker
  - It is not clear to me what the relationship between the worker, owner, and publickey are.  Is the key unrelated to worker and owner addresses or can it sign messages for one of them?
  - This TODO on `DePledge`: "Do both the worker and the owner have the right to call this?"  
- [x] At some point we need to specify Proving Period length as a function of sector size (and anything else relevant)
- [ ] We need to move asks offchain in the spec

**Comment by whyrusleeping** [comment]
> Motivation behind worker account in the comments above the field in the miner actor would resolve lots of confusion

@ZenGround0 is the owner worker distinction here not sufficient? https://github.com/filecoin-project/specs/blob/master/mining.md#owner-worker-distinction


the rest sgtm, will send a PR

**Comment by ZenGround0** [comment]
@whyrusleeping yup I missed that, just what I was looking for

**Comment by whyrusleeping** [comment]
Made a new issue for offchain asks: https://github.com/filecoin-project/specs/issues/309

and #60 should address the collateral stuff when resolved.

Closing this issue out now
