### ISSUE TITLE
Complete Design of Multilane Payment Channels

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#300]
[Existing spec is here](https://github.com/filecoin-project/specs/blob/master/payments.md#multi-lane-payment-channel)

The withdraw method is currently a stub containing the TODO: " this ones tricky, withdraw funds without closing it out entirely..."

This is needed for a "complete" version of the storage protocol, but go-filecoin currently is running with basic channels until this construction is fully designed and merged to the spec.

**Comment by whyrusleeping** [comment]
@ZenGround0 the Withdraw method is not necessary to implement this, you can make the entire system work without it, its just a nice 'boost' to allow rebalancing funds without closing the channel out (and its use should be rare). Everything else is there and should be implemented.

**Comment by mishmosh** [comment]
I think this is covered now in https://filecoin-project.github.io/specs/#algorithms__payment_channels. @ZenGround0 can you close this issue if you agree?
