### ISSUE TITLE
Allow small grace period for timestamp checking

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#308]
We currently check that received blocks do not have a timestamp in the future. This could cause problems if nodes have out of sync clocks. We should probably check that the blocks arent more than ALLOWABLE_CLOCK_DRIFT in the future. This value could probably be as far as a minute, since we just want to know that miners arent submitting chains super far in the future.

However, doing this means that miner implementations who always use their local time for the time stamp could produce blocks that *before* their parents. (if one miner is a minute ahead of the next miner).

Bitcoin timestamps just need to ensure that the timestamp is greater than the median time of the last 11 blocks: https://en.bitcoin.it/wiki/Block_timestamp

https://medium.com/@lopp/bitcoin-timestamp-security-8dcfc3914da6

**Comment by merced** [comment]
As miner, I would think the strategy would be setting blocktime = blocktime-ALLOWABLE_CLOCK_DRIFT while mining. And this would still cause validation fail for certain nodes and make their local chain out of sync with majorities of the net.

**Comment by whyrusleeping** [comment]
Yeah, though if you make a block that a large portion of the network rejects, you're just wasting your time.

**Comment by anorth** [comment]
The block timestamp is checked against two things:
- no less than BLOCKTIME past the parent tipset's timestamp
- no more than DRIFT past "now"

Is the grace period referring to the latter, or to both?

Our situation might be a bit different from bitcoin since, until VDFs, this delay is a critical part of maintaining block time (while bitcoin POW difficulty gives a reasonable expectation value of average block times). And when we have VDFs, my understanding is that there will be much less variance in the computation time than a traditional POW, so we might support tighter bounds.

**Comment by whyrusleeping** [comment]
@anorth referring to the latter.

The problem that @merced points out is that if you allow block timestamps to be `X` less than the block time, then a malicious miner would always make a block `block_time - X` ahead, instead of the full `block_time`. If you *dont* allow this, then miners may receive a block that is `DRIFT` in the future, and when they go to make a block, they will either have to wait longer, or lie and put a future timestamp on their block. 

In any case, nodes in the network need to have fairly well synchronised time, bitcoin and ethereum (especially ethereum) require all participating nodes to run ntp (or some other time sync service) to ensure their clocks are as close as possible.

**Comment by whyrusleeping** [comment]
Also agree that bitcoins model won't work for us, but its good background.

Additionally, worth reading is snow white: https://eprint.iacr.org/2016/919.pdf which uses a similar timestamping mechanism (though I don't think they've had to deal with the complexities of putting that to work in a real system)

One thought is to bound block creation by an expected number of blocks over a certain period of time. A time `T`, we expect there to be `T - GenesisTime / BlockDelay` blocks created. If we see significantly more than expected, then maybe we shift the delay higher, and if we see fewer than that, shift the delay lower? This is effectively a difficulty adjustment.

> And when we have VDFs, my understanding is...

Unfortunately, VDFs don't do a good job of setting a tight bound on the block time. VDFs do a great job of protecting against 'fortune teller' attacks, where an attacker looks into the future on their own, creating blocks and ignoring timestamp rules in their private chain, in order to find an optimal decision tree. Even with highly advanced and expensive hardware, you can expect variances in VDF evaluator performance of up to 10x (which is the maximum we're targeting for the VDF ASIC project).

**Comment by dignifiedquire** [comment]
Fixed in #340
