### ISSUE TITLE
Moving asks off chain

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#309]
We've talked about it for a while. We should probably do it. Placeholder issue for now.

**Comment by pooja** [comment]
One plan for implementation is here: https://github.com/filecoin-project/go-lotus/issues/177

**Comment by pooja** [comment]
We need to answer whether storage market asks will be on or off-chain and spec it so all implementations can implement the same thing.

**Comment by mishmosh** [comment]
Asks are off-chain now, both in design (https://filecoin-project.github.io/specs/#systems__filecoin_markets__storage_market) and implementation (https://github.com/filecoin-project/go-fil-markets).
