### ISSUE TITLE
Define how power & sectors are stored on chain and used in consensus

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/specs#31]
We are switching to using sector count instead of bytes for power calculations in https://github.com/filecoin-project/go-filecoin/pull/894. 

This needs at least three things before finalizing for testnet

- [ ] decide if we want to do this going forward, and articulate why
- [ ] update spec accordingly
- [ ] define how changing the sector size works

**Comment by pooja** [comment]
Closing b/c it's been resolved
