### ISSUE TITLE
Clarify encoding of proof bytes

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#313]
https://github.com/filecoin-project/specs/blob/master/data-structures.md#basic-type-encodings has statements like `SealProof is a 384-element array of bytes` without further description. https://github.com/filecoin-project/specs/blob/master/proofs.md has some more detail in pseudo-go but it's not clear how these line up.

I would suggest that the encodings be documented along with the more detailed structure, although if there are reasons to want to keep that big list of encodings, a link and description of how the structures are turned into bytes (when not CBOR) could be enough.

I'm filing this issue by request, but am not the right person to state our exact needs. @laser @acruikshank perhaps you can help here?

**Comment by dignifiedquire** [comment]
these should be documented only in the proofs spec as they are subject to change and not stable yet. The rest of the chain should treat them as an opaque fixed sized byte array.

**Comment by acruikshank** [comment]
From a practical go-filecoin perspective, I'd rather consider a seal proof (or any proof) to be an arbitrary number of bytes that we never de-serialize and let rust-proofs deal with the details. Understanding anything about the structure of the proof would unnecessarily couple the go-filecoin implementation to the proof implementation.

**Comment by dignifiedquire** [comment]
@acruikshank that sounds right to me, though we still need to spec the proofs, as part of the spec, which is what I meant with my comment.

**Comment by laser** [comment]
For what it's worth:

> SealProof is a 384-element array of bytes

The above statement is not correct. A seal proof (like a PoSt proof) contains 192 * N bytes, where N is the number of partitions used when creating the proof. The type of `SealProof` (and `PoStProof`) should be `[]byte`, not `[384]byte`.

**Comment by laser** [comment]
(and I too suggest that the Filecoin node treat the proof bytes as opaque)

**Comment by porcuquine** [comment]
I think we're in agreement. Everything @laser said is correct (at least for now). @laser, I think you have the best understanding of how `go-filecoin` interacts with the possibility of variable proof sizes. Would you mind either making the spec change required here or else feeding me some verbiage that will allow me to write this?

Specifically, the goal is to avoid either introducing extraneous concepts, or omitting detail that will be needed so implementers can handle and/or validate the size of these opaque binary proofs.

**Comment by laser** [comment]
@porcuquine 

> Would you mind either making the spec change required here or else feeding me some verbiage that will allow me to write this?

Yep, I will make the required spec changes.

**Comment by laser** [comment]
@dignifiedquire - As of the merge [of this PR](https://github.com/filecoin-project/specs/pull/323), you can consider this issue resolved. Would you please close it?

The spec now says:

> PoStProof is an opaque, dynamically-sized array of bytes.

**Comment by dignifiedquire** [comment]
thank you @laser
