### ISSUE TITLE
Miner Profiles

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#32]
Big Filecoin miners will be fairly serious business ventures. As such, they will likely want a way to advertise information about themselves, such as a website link, gpg key, name, country, or other information about their services. 

I think that it makes a lot of sense for this information to be stored directly in the miner actor (or, a cid of the information could be stored in the miner actor). This would allow different filecoin UIs to display some more interesting information about each miner.

We should figure out a base format for this information and suggest miners fill out pieces they care about. Miners can probably add whatever fields they want to, but setting the conventions early will make things easier.

**Comment by pooja** [comment]
Related to #178

**Comment by mishmosh** [comment]
Closing - #55 is a more recent take on same need.
