### ISSUE TITLE
specify the GenerationAttackTime function

### ISSUE THREAD

**Issue by laser** [filecoin-project/specs#322]
The [spec](https://github.com/filecoin-project/specs/blob/master/actors.md#commitsector) shows that the [`SubmitPoSt`](https://github.com/filecoin-project/specs/blob/master/actors.md#submitpost) and [`SlashStorageFault`](https://github.com/filecoin-project/specs/blob/master/actors.md#slashstoragefault) methods rely on a function called `GenerationAttackTime`. We need to specify this function.

**Comment by pooja** [comment]
We will spec this this week

**Comment by nicola** [comment]
Old issue
