### ISSUE TITLE
Proposal: simplify handling of message value, fees, and collateral in SubmitPost

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#329]
A miner invoking [StorageMiner.SubmitPoSt](https://github.com/filecoin-project/specs/blob/master/actors.md#submitpost) must calculate and attach a message `Value` that is sufficient to cover computed fees for lateness and temporary sector failures, which SubmitPost checks. A `Refund()` is intended to return any excess value to the caller. A separate calculation computes a penalty from the miner's pledge collateral for failed sectors, and an amount equal to the fees plus the penalty is burned.

However, pledge collateral requirements are dynamic and a miner actor's posted collateral is simply its balance (see #60). A miner is invoking `SubmitPoSt` on itself (i.e. the miner worker signs the message with the miner's key[1]), so the message value also comes from ... its balance! Any refund goes back to the same place! Message value is implicitly transferred to a message's receiving actor before any method invocation, so in this case is a no-op transfer. This is not an effective way of forcing fee payment from funds *additional to* collateral.

This logic would be much simpler if the late and temporary failure fees were treated the same as the penalty for permanently lost sectors and simply burnt from the miner actor's balance without any explicit reference to message value. This could cause a miner to become under-collateralised, but *this can happen anyway* due to the dynamic collateral requirement or a permanent sector failure. This shouldn't prevent the PoSt: we want to encourage valid PoSting as must as possible.

[If we *did* want to prevent submission of a PoSt that would incur penalties that would bring a miner under collateral requirements, this calculation should still ignore the message value and be phrased in terms of `vm.MyBalance()` (which includes the message value).]

A miner wishing to avoid the under-collateralised state (why would they? it's essentially a loan against future block rewards) can replenish collateral with a transfer *from some other account*, either before or after submitting PoSt. Alternatively, collateral is expected to be replenished by garnishing block rewards. We could consider additional incentive (interest payments) to top-up collateral quickly if this is insufficient.

As well as simplifying the fee/penalty calculations, this would simplify implementation because we'd probably not bother calculating penalty fees when submitting a PoSt and just fix up the collateral shortfall after the fact (if at all).

[1] I could be wrong here, but this is my understanding. The miner owner's key should not be required online, so regular miner messages use the miner's key, and hence the miner actor's balance.

**Comment by whyrusleeping** [comment]
> so the message value also comes from ... its balance! 

No, the message value comes from the miner worker account balance.

**Comment by anorth** [comment]
Ok, thank you. So there are *three* actors involved in a miner: the owner account actor, worker account actor, and the miner actor. The spec does mention that there are two "controller" addresses, but the relationship of these to the miner worker actor itself isn't so clear. A bunch of places just say "the miner" and would benefit from disambiguation between the worker actor and miner actor. I'll work up a PR to clarify.

So, please correct me if I'm wrong here:
- A miner actor has no associated key pair and its address is not derived from a public key
- Thus no message from an account actor can directly spend the miner actor's balance: it can only invoke a method (which could then transfer the balance)
- A miner's collateral will be the miner actor's balance (not worker or owner accounts')
- The SubmitPoSt is message is from the miner worker actor to the miner actor, and value is transferred to the miner actor's balance before the message executes.

That said, some of my proposed simplifications still stand. In particular, since value is implicitly transferred to the miner actor's balance, which represents its collateral, it would still be simpler to express late fees and temporary fault fees in terms of the balance only, and any penalty burnt from the balance. The refund is a useful thing though: in case the resulting balance is more than enough, up to msg.Value can be refunded immediately rather than locked up.

I still propose that we don't want to prevent the submission of a correct (but late or fault-carrying) PoSt if the miner is under-collateralised, regardless of message value.

And to answer myself:
> A miner wishing to avoid the under-collateralised state (why would they?)

An under-collateralised miner cannot commit a *new* sector until they post required collateral for it.

**Comment by pooja** [comment]
Todo for us: Disambiguate between the worker actor and miner actor

**Comment by whyrusleeping** [comment]
> I still propose that we don't want to prevent the submission of a correct (but late or fault-carrying) PoSt if the miner is under-collateralised, regardless of message value.

If we do that, a miner could be permanently undercollateralized, so long as they don't add any new sectors.

We could say that if a miner becomes undercollateralized in this way, their power is zero until they become properly collateralized, and that they cannot submit a post, or commit new sectors while undercollateralized either. But that adds more complexity to all of this.

**Comment by anorth** [comment]
> If we do that, a miner could be permanently undercollateralized, so long as they don't add any new sectors.

My point is that this is already the case, regardless of late fees. A miner can submit on-time PoSts and remain or become progressively more under-collateralised (as per-sector collateral requirements increase with time). Preventing the submission of PoSts just makes it more likely that the miner ends up with the much more serious fault of being later than the generation attack time, leading to loss of power and slashing. I don't think a late PoSt should be explicitly discriminated against here.

I don't think we want to strip power for being under-collateralised, because winning a block reward is the primary way we expect collateral be to topped up. I agree we don't want to add complexity, I'm trying to remove it.

*However*, since posting this proposal there has been other talk about maybe we shouldn't be penalising pledge collateral for PoSt faults (due to the huge operational risk). In that case `SubmitPoSt` would not be touching pledge collateral at all and I withdraw this proposal in favour of requiring a fee to be attached to the message.

**Comment by pooja** [comment]
Since we decided to penalize storage collateral instead of pledge collateral, we're going to move forward with message fee version (which is the status quo).

@anorth Feel free to reopen this issue if this doesn't address your question
