### ISSUE TITLE
clearly define serialization for actor storage`

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#330]
Right now we're just cbor marshaling the structs that are declared in the actors.md file. We should serialize these more compactly, possibly using FCS (though, the thought of allocating a multicodec per type is unpleasant)

**Comment by whyrusleeping** [comment]
cc @dignifiedquire

**Comment by dignifiedquire** [comment]
- that would technically be a cbor tag not a multicodec, right?
- we could have one special fcs type which links to the schema, instead of declaring what it is, that would make this more extensible, while removing the repeated keys.

**Comment by dignifiedquire** [comment]
will be solved with 352
