### ISSUE TITLE
The purpose of 'Asks', and 'maybe we should just have miner prices'

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#34]
Moving the storage market off-chain means that there are no on-chain bids or deals. But, asks are still (currently) on-chain. They are what we are using to advertise price, and a miner may have multiple asks. Previously, we also specified how much space each ask was for, separately from the amount of space that miner had pledged. As each deal was made, this amount was decremented.

With an off-chain storage market, asks are pretty pointless. We could instead just have each miner set a price for all their storage (as there isnt really any reason for an individual miner to have different prices since theres no way to provably distinguish between different types of storage the miner has locally).

Generally, price discovery needs more thought. I will follow up in another issue

**Comment by pooja** [comment]
Asks are impt b/c we do want to have a two-sided market.

Currently, we don't have real asks, but we will eventually.
