### ISSUE TITLE
ProvingSet and NextDoneSet types

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#346]
It is my belief that the miner actor's `ProvingSet` and `NextDoneSet` fields should actually be `Bitfields` encoding sets of integers rather than `SectorSets`.  This way we don't redundantly store the commitments that we need to store within sector sets.  The proving set and done set should only index into the more expensive sector set.  I think this is totally safe because the CommitSector spec prevents adding a sector to the sector set if the id overwrites an existing id.

@whyrusleeping if you see this and agree give me a thumbs up.  If you disagree let me know what I'm missing.  If I don't hear back in a while I'll throw up a speculative spec PR.

**Comment by pooja** [comment]
This is already done in master.

@ZenGround0 please create a new issue if you're looking for something else!
