### ISSUE TITLE
Where are the best examples of the Go pseudo-code used in the specs?

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/specs#347]
Also, we could add something like a "Definitions, symbols and abbreviations" section. It might be useful both for reading and writing the specification in this repo.

**Comment by mishmosh** [comment]
> Where are the best examples of the Go pseudo-code used in the specs?
`StorageMarketActorState` is a good example: https://filecoin-project.github.io/specs/#storagemarketactorstate-implementation

> we could add something like a "Definitions, symbols and abbreviations" section.
There's now a glossary section: https://filecoin-project.github.io/specs/#glossary. Feedback welcome :)
