### ISSUE TITLE
Clarify which type of collateral is penalized by ArbitrateDeal

### ISSUE THREAD

**Issue by pooja** [filecoin-project/specs#353]
ArbitrateDeal currently looks to penalise both pledge and storage collateral, which doesn't match faults.md. Which one is it? And make it consistent.

Originally noted in https://github.com/filecoin-project/specs/issues/306

**Comment by anorth** [comment]
I'm pretty sure it's intended to be storage collateral, and the penalty is paid to the client. The world of deals is separate from the world of pledges and commitments.

**Comment by anorth** [comment]
The ArbitrateDeal spec now only refers to storage collateral, so I think this is good now. https://github.com/filecoin-project/specs/blob/master/actors.md#arbitratedeal
