### ISSUE TITLE
Standardize the definition of height across the protocol

### ISSUE THREAD

**Issue by pooja** [filecoin-project/specs#357]
In EC, height is not incremented for rounds in which null blocks are produced. Height is only incremented when at least one block is found in the round.

However, elsewhere in the spec, e.g. in proofs, height is incremented for every round, including those with null blocks since height is used as a way to measure the passage of time.

We should reconcile these differences and update expected-consensus.md and proofs specs, at a minimum.

**Comment by sternhenri** [comment]
Done in https://github.com/filecoin-project/specs/pull/351
