### ISSUE TITLE
Spec process proposal

### ISSUE THREAD

**Issue by decentralion** [filecoin-project/specs#36]
# Spec Update Process

This is a proposal for creating a standardized process around documenting and
updating the Filecoin spec.

## Intent

We need to produce a technical specification of the Filecoin network and
protocol. Without a spec, it will be difficult to accurately communicate (or
come to consensus on) how Filecoin works, and it will be nearly impossible to
write additional valid Filecoin clients.

Producing a spec is challenging. Like all documentation, writing it takes
considerable effort, and it must be continually maintained to stay current.
This proposal aims to describe a v0 process for writing and maintaining the
spec. This is explicitly *not* the final process; see [EIP 1] for an example
of what a fully developed spec process would look like. This spec proposal is
much lighter weight.

[EIP 1]:https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md

## Requirements

- It must be possible to write a Filecoin client using just the spec
- The spec needs to communicate design intent
- The spec needs to have a clear "lifecycle" that makes changes to the spec
  visible before merging, so that interested parties (e.g. developers and
  users) can provide feedback and plan accordingly
- We need to synchronize the spec with the behavior of go-filecoin
- We need to accomodate that the current behavior of go-filecoin is mostly
  unspecified, so the spec needs to catch up

## Proposed Process

Updates to the spec will happen through a 3 part process:
- Proposal
- Draft
- Spec

### Proposal

A **proposal** is a GitHub issue posted in this repository
[filecoin-project/specs](fp/specs). The purpose of a proposal is to communicate
high-level intent to change the protocol. Proposals do not need to be at a very
high level of detail, and should be written early in the process towards
changing the spec. The GitHub issue number assigned to the proposal will be
used to identify and reference to it.

### Draft

A **draft** is a markdown document located in the master branch of this
repository, within the `/drafts` folder. The title of the markdown document
should start with the number of the proposal that spawned it.

A draft is a concrete suggestion for a change to the spec, and should be
written at the same level of detail prevailing in the spec. Drafts should merge
easily (i.e. consensus from the team is NOT required to merge the PR). 

Each draft should be identified by the GitHub issue number of the proposal that
spawned it.

### Spec

Once a draft has been officially accepted into the spec, the specs owners
(@whyrusleeping and @bvohaska) will merge the draft into the spec code. The
draft can be left in the repository for historical tracking.

[fp/specs]: https://github.com/filecoin-project/specs/

## Catching Up

We need to synchronize the spec with go-filecoin, and write it at a high level
of detail. As of Oct 2018, we have a lot of catching up to do. For now, there
is a lot of Filecoin behavior that is unspecified.

Until we have a v1 spec, the requirements for the spec are relaxed. We will not
require that every draft be implemented at a high level of detail: it must only
improve on the current document. Also, we are not yet blocking feature
development in go-filecoin on their details being fully specified, although we
should encourage anyone involved in developing unspecified features to go
through spec review first.

Once we have a v1 spec, we'll tighten up the requirements for merging a draft,
and will start blocking any unspecified changes to go-filecoin.

---
Note this is just a proposal. Comments are welcome, once we have some consensus we can make it into a draft and then get it merged as an early piece of the spec.

**Comment by pooja** [comment]
We now have one.

**Comment by bvohaska** [comment]
@pooja: Where is this documented?

**Comment by decentralion** [comment]
@bvohaska: here i believe: https://github.com/filecoin-project/specs/blob/master/process.md

**Comment by pooja** [comment]
Yup! ^ @whyrusleeping If you were thinking of something else here
