### ISSUE TITLE
Should we include TipSets in the data-structures spec?

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/specs#360]
Some operations used elsewhere in the spec, eg the mining spec, lead one to think that the TipSet is an actual data structure as opposed to just an abstraction.

We should either:
1. add it to the data-structures spec 
1. replace the likes of `chain.GetAncestorTipset`,  or `TipSet.State` in favor of equivalent block operations
1. simply explicit that TipSet is an abstraction and all TipSet operations are actually performed in terms of the underlying blocks (i.e. TipSet.State means parent rootState + all block messages for block in TipSet).

I would advise option 3

**Comment by sternhenri** [comment]
cc @pooja @whyrusleeping

**Comment by sternhenri** [comment]
Took a small stab in https://github.com/filecoin-project/specs/pull/361

**Comment by mishmosh** [comment]
I think we've done this (via 3): https://filecoin-project.github.io/specs/#tipset. Feel free to re-open if there's more to discuss though.
