### ISSUE TITLE
Scalability for deal arbitration

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#380]
The actors spec contains the following TODO for `ArbitrateDeal`:

> This method, as currently designed, must be called once per sector. If a miner agrees to store 1TB (1000 sectors) for a particular client, and loses all that data, the client must then call this method 1000 times, which will be really expensive.

**Comment by pooja** [comment]
@anorth we already have https://github.com/filecoin-project/specs/issues/89 open and @whyrusleeping is looking into it this week. Does this issue cover something different?

**Comment by anorth** [comment]
That's fine, thanks. It would be great if TODOs in the spec could link to the relevant issue so we can know it's being tracked and where to find the discussion.
