### ISSUE TITLE
Support arbitration of more than one deal for the same data

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#388]
Clients in general are expected to be able to request the same data be stored more than once by a miner, and the proving system verifies that multiple distinct replicas are indeed created.

As I understand it, commP is computed by the client and identifies the data to be stored. The `ArbitratedDeals` map is keyed by commP. This means that a client can only arbitrate a single deal for a commP, even if the miner has in fact defaulted on multiple.

**Comment by whyrusleeping** [comment]
Would be a bit weird to store the same piece with the same miner, the client would have to check that they werent both placed in the same spot on the same sector. Distinguishing that might actually be difficult.

As a slight aside, clients are expected also to be erasure coding their data, which would result in different commitments for what is effectively the 'same' piece of data.

**Comment by mishmosh** [comment]
Obsolete, no more arbitration. Clients can ProposeDeal to multiple miners.
