### ISSUE TITLE
Filecoin Spec Work

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#39]
Using this issue to track work that needs to be done in order for the 'spec' to be complete.

- [x] process on how to sync the blockchain
- [x] hello protocol
  - https://github.com/filecoin-project/go-filecoin/issues/1252
- [x] message processing (aka, how do i do state transitions?)
  - https://github.com/filecoin-project/go-filecoin/issues/1259
- [x] retrieval market
  - https://github.com/filecoin-project/go-filecoin/issues/1283
- [ ] Document the proofs
  - [x] Document interfaces
    - https://github.com/filecoin-project/specs/pull/133
  - [ ] Document specifics
- [ ] 'how to run a node' should be documented
  - document started [here](https://github.com/filecoin-project/specs/blob/master/operation.md)
  - [ ] https://github.com/filecoin-project/go-filecoin/issues/1312
- [ ] Local data storage
  - Should document *what* is stored, not how its stored
  - https://github.com/filecoin-project/go-filecoin/issues/1311
- [ ] cbor CHAMP documentation
  - https://github.com/filecoin-project/go-filecoin/issues/1268
- [x] need link to 'cbor-ipld' spec
  - [ ] https://github.com/ipld/specs/pull/73
- [ ] How do account IDs work?
- [x] message signatures
  - https://github.com/filecoin-project/go-filecoin/issues/1267
- [ ] payment channel usage
- [ ] IPLD Spec
- [ ] libp2p Spec
- [ ] 'How to use the spec' document
  - [ ] Link to the spec process in the spec

**Comment by pooja** [comment]
Closing because we have specific issues for things that haven't been done
