### ISSUE TITLE
add treasury and vesting to spec

### ISSUE THREAD

**Issue by decentralion** [filecoin-project/specs#391]
As drafted in #325, we need a way to calculate the total available FIL, e.g. via `availableFil := minedFil + vestedFil - burnedFil`. @anorth suggested using a single treasuryActor, which is the source of block rewards, vested FIL, and to whom burned FIL returns. in that case, checking available FIL would be as simple as subtracting the total token supply from the current balance of the treasury actor. 

We already have a treasury actor who starts with the full token balance, and is transfers out block rewards. So the main thing to spec is the vesting. Vesting is a little complicated because there are multiple different vest schedules (6 month, 1 year, etc).

There are a few ways we could encode this:
- The treasury actor directly contains the vesting logic, and effects transfers to every vestee directly
- There is a single vesting actor which receives funds from the treasury actor, and effects transfers to the vestees
- There is a vesting actor for each vest schedule, each of which receives funds from the treasury actor, and effects transfers to vestees

These are basically different tradeoffs of putting the complexity in the treasury actor vs. delegating to other actors. Assuming we go with the delegated approach, we can also decide when the treasury actor sends the funds: either all at once in the genesis block, or incrementally (e.g. monthly) as the funds vest. The first approach is to implement, but it makes calculating the total available FIL a little harder (because finding the available FIL now requires iterating over each vesting actor).

We should also give some thought to how vested funds are released. A simple approach is to have each vesting actor transfer the vested FIL to a receiving account every month, but this might spam the network with transactions, and it's not clear how the transaction fee should be chosen. A better approach would be to architect it so that each vestee chooses when to withdraw funds, and can choose an appropriate transaction fee at that time.

**Comment by anorth** [comment]
I suggest that vesting means that funds become available to be withdrawn, but does not actually automatically send the funds anywhere. Things are much simpler to reason about and code if an explicit network message is required to move funds (or change any state in general). The receiver of funds clearly has the incentive to send that message in order to receive their funds.

Minor note: burnt funds go to the burnt funds actor (id 99), which I think is fine.

**Comment by taoshengshi** [comment]
> I suggest that vesting means that funds become available to be withdrawn, but does not actually automatically send the funds anywhere. Things are much simpler to reason about and code if an explicit network message is required to move funds (or change any state in general). The receiver of funds clearly has the incentive to send that message in order to receive their funds.
> 
> Minor note: burnt funds go to the burnt funds actor (id 99), which I think is fine.

good suggestion! but one minor comments regarding the transaction fee of vestee's requiring to move funds: is this scenario transaction fee needed?  and where does the transaction fee take out      for a fresh account ?  or deduct from vesting fund ?

**Comment by decentralion** [comment]
A transaction fee is needed so that people can't spam the network with tiny vest withdrawals. However, we should make the transaction fee get deducted from the vestee's vested FIL, not from the vestee's destination wallet, so someone who has vested FIL but not liquid FIL can still withdraw their vest.

**Comment by taoshengshi** [comment]
> A transaction fee is needed so that people can't spam the network with tiny vest withdrawals. However, we should make the transaction fee get deducted from the vestee's vested FIL, not from the vestee's destination wallet, so someone who has vested FIL but not liquid FIL can still withdraw their vest.

make sense, sir.
