### ISSUE TITLE
SUGGESTION: rename "storage collateral" to "deal collateral"

### ISSUE THREAD

**Issue by laser** [filecoin-project/specs#392]
In the spec, the term "storage collateral" refers to the FIL that the storage miner owes the clients with which it has active storage deals. The term "storage collateral" does not refer the FIL that a storage miner locks up when committing storage to the network. 

Personally, I find the term "storage collateral" to be confusing. I humbly suggest that you change "storage collateral" to "deal collateral."

**Comment by laser** [comment]
@dignifiedquire ^

**Comment by anorth** [comment]
💯

**Comment by dignifiedquire** [comment]
suggestion: keep "storage collateral", rename "pledge collateral" to "consensus collateral"

**Comment by pooja** [comment]
1. Make sure there are no instances of "collateral" alone, should either be storage or consensus collateral
2. Rename "pledge collateral" to "consensus collateral"

**Comment by anorth** [comment]
I wanna re-affirm preference for the original suggestion:
- pledge/deal names the collateral after what it is securing, who is wronged, who it can be claimed by. 
- consensus/storage names the collateral after what part of the system is inspected. 

The latter distinction is much more tenuous. If we discovered a *malicious* act that a miner could take related to their storage or proofs, such that they could fake power, we would penalise the pledge collateral, not the storage collateral. They might still be holding up their deal with clients.

**Comment by pooja** [comment]
I'm fine to change storage collateral to deal collateral. Don't feel strongly on this.

**Comment by jbenet** [comment]
- in the future, there _will_ be other collateral for types of deals, so "deal collateral" is not a good name for what today we call "storage collateral".
- I would be OK with changing it to "storage deal collateral", but some may feel this is strictly worse as it is more typing.

**Comment by taoshengshi** [comment]
I support @dignifiedquire 's suggestion, illustrated with picture as below:
![tech-discussion](https://user-images.githubusercontent.com/33315004/61439260-c56b7d80-a973-11e9-9c42-3ca0c04c543e.jpg)

**Comment by anorth** [comment]
I'm also ok with "storage deal collateral", or I guess the "consensus collateral" term too.

**Comment by laser** [comment]
OK, thanks for the input. I will create a PR changing:

- "storage collateral" to "storage deal collateral"
- "pledge collateral" to "consensus collateral"
