### ISSUE TITLE
Remove 'algorithm' header and section from EC spec

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/specs#405]
It gives a preview of what will be later in the file, but I find it doesn't add much/is redundant. 

I think you added it based on user feedback @pooja, so feel free to ignore if it is in fact useful.

**Comment by pooja** [comment]
I think having a high-level description of the algorithm in words is extremely useful before diving into pseudocode and the details! I'd leave as is!

**Comment by sternhenri** [comment]
sold.
