### ISSUE TITLE
Can miners get paid before the end of the proving period?

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#419]
It's unclear from the spec when miners get paid (or better, when they can unlock money from their payment channels) and how often (every X blocks? after a proving period). According to the go-filecoin implementation miners get paid every X blocks, regardless of their proof submission.

**If this is the case:**
This means that there are some blocks before a proving period for which miners can get paid, this could lead to an uncomfortable situation: the miner submit a post and then deletes the data and still get paid.

- Shouldn't the payment channel only unlock money when a proof appears on chain?
- Is the concern that I am describing a real concern?

**Comment by nicola** [comment]
With this fix proposed by @whyrusleeping:
> one trivial fix is saying a miner who is tardy on their PoSt cant cash out payment channels

now, client can set the payment cadence to be at the end of every proving period and miners can't be paid if they haven't submitted proofs.

**Comment by anorth** [comment]
A miner should be able to cash out payment vouchers that are timestamped *prior to the last proof they have actually submitted*. We shouldn't just lock up all channels unconditionally because a miner misses a PoSt. But if we have a `LastPoSt` state variable or similar mechanism, this seems easy.

**Comment by taoshengshi** [comment]
I think payment channel essentially is multi-sig smart contracts which distribute award/fund among contracting parties, and blockchain essentially is time/clock machine which trigger the payment channel to take action for arbitration. are we in same page?

From micro payment channel point of view, miners could `get` micro paid before the end of the proving period but the paid is lock up in the contracts (is here contracts same meaning with alex 's payment vouchers ? ) when and only when proving period come to end contracting parties could ”real“ get paid, and if miners missed Proof, they can't get the lockup paid .

![paymentchannel](https://user-images.githubusercontent.com/33315004/62344701-ad722d00-b521-11e9-866d-7d69b45738f7.jpg)
But micro payment channel 's applied scenario is offchain micro payment tracking and final statement, which fit best for file uploading and downloading charged by data size and bandwidth consuming. Base on the IPFS storage model and marketing design, user propose deal and import data into filecoin network, where does the micro payment happens with？ how does filecoin deal with below scenario?
1. upload(import and propose deal)
2. modify the data (delete old data and import again?)
3. upload again (import and propose deal)
4. download (retrive, payment channel ? how do deal download partially or attacks？)
5. user store data only for three months
6. user store data for three months, renew contract for next three months
7. user propose deal but does not store data(or will some time later)
8. user could modify the stored data during one proving period

**Comment by mishmosh** [comment]
Answer to the initial question is no, miners only get paid up to the last PoSt they have submitted.
