### ISSUE TITLE
Can a deal be renewed more cheaply?

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/specs#428]
This came up while walking through a storage scenario with @autonome.

Let's say client wants to store data "forever", or at least many years. In Filecoin, that requires a series of deals. For each new deal the client must have a running node, to imported (or re-import) the same data into Filecoin again and transfer it again over the internet. This is more cumbersome than current storage alternatives which have a "push and forget" model.

Are there ways to make deal renewal more efficient, either with the same miner or different miner? If it's the same miner, could parts of the commitsector message be reused?

**Comment by taoshengshi** [comment]
@mishmosh is this topic similar/related i commented in this [thread](https://github.com/filecoin-project/specs/issues/419)?

**Comment by whyrusleeping** [comment]
Renewal agreements can be redone entirely off-chain. The simplest version involves a client just sending more sector-locked payment channel vouchers to the miner. In this situation, the miner can continue storing the data and keep getting paid for it. The downside is that if the miner drops the data, the client cannot slash the miner for this (As that requires a deal with an extended duration)

The slightly more complicated case is the client and miner can communicate and resign a new deal with an extended duration. This can be done entirely off-chain, allows the  miner to keep getting paid, and allows the client to slash the miner if they end up dropping the data before the agreedupon end date

**Comment by mishmosh** [comment]
Off-chain renewal is a fair stopgap, but won't be competitive at scale. It effectively pushes the renewed content into a second class of riskier storage, lacking the storage collateral guarantees of a fresh deal.

Unless there is a "renewal" deal type that has other levers to compensate?

**Comment by mishmosh** [comment]
This informed the separation of data transfer from storage deal. You still have to enter into a new deal, but this does provide foundational support for transferring data from existing miner. Closing bc this issue has served its purpose.
