### ISSUE TITLE
define SectorID type

### ISSUE THREAD

**Issue by laser** [filecoin-project/specs#437]
The [data-structures](https://github.com/filecoin-project/specs/blob/master/data-structures.md#sectorset) section of the specification doesn't say anything about this type, and the `SectorSet` data structure (indexed by sector id) isn't specified either. I suggest an unsigned, 64-bit integer (which is what `go-filecoin` and the sector builder use today) for SectorID.

Quoting @whyrusleeping 

> [...] the definition of the SectorID is missing. It should just be an integer. Technically up to 31 bytes long, but I think for all practical purposes we can just use a uint64 as we will never have a single miner with 2^64 sectors

Relevant comment [here](https://github.com/filecoin-project/go-sectorbuilder/issues/5#issuecomment-515815855).

**Comment by whyrusleeping** [comment]
Sounds good to me!
