### ISSUE TITLE
Take care to separate abstract concepts and their concrete definitions

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#44]
In general, we should take care to not conflate abstract concepts (PoRep, EC, State Machine) with the concrete implementations. For example, Expected consensus doesnt necessarily care about storage power, or proofs of spacetime. That is (for lack of a better name) 'Filecoin Consensus'. 

Another more actionable example is that we should find a name for our specific implementation of each proof. It is not exactly correct to say that "Proof of Replication ... produces a SNARK proof". Proof of replication simply proves in some way that a unique replica of some input data has been created. The description at the top of the proofs.md spec file does this well, it's just later in the doc where we give a concrete definition that we should phrase it differently. One simple proposal would be to just call this SNARK construction "PoRep-1" and say that "PoRep-1 ... produces a SNARK proof" (and so on). Obviously someone with a knack for naming could pick something better than a numeric naming system.

cc @porcuquine @nicola

**Comment by pooja** [comment]
A general note, which participants have ack'ed
