### ISSUE TITLE
Block size reduction low hanging fruit: one ticket VRF per header

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#443]
Currently each [ticket](https://github.com/filecoin-project/specs/blob/master/data-structures.md#ticket) data structure includes a VRF proof which is hashed and fed as input to a VDF.  

The purpose of this VRF is to provide high quality, unbiased randomness.  I conjecture we can get just as "good" randomness with fewer bytes in the case where there are one or more null blocks.  

The idea is to simply chain VDF proofs together on top of the previous block's VRF output, and then run the final VDF input through a VRF only once.  As a result the "ticket array" would become a VDF (y, pi) array and a single VRF output.

**Comment by sternhenri** [comment]
We agree that this would allow for potential optimization for a miner running multiple sybils (ie share VDF outputs pre and post VRF run)?

Also linking to https://github.com/filecoin-project/specs/issues/399#issuecomment-525463383 specifically where the idea of dropping tickets altogether (in favor of a counter) was broached (and abandoned).

**Comment by mishmosh** [comment]
We removed VDFs so there are no more multiple tickets. So got this one (one ticket per header) for free ;)
