### ISSUE TITLE
Resolve TODOs around PoSt and fault handling

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/specs#449]
In #332 we punted on some of the finer details on recovery and penalization of fault handling. This needs to be detailed and figured out.

Some things we know need to be defined (not comprehensive)

- [ ] update `SubmitPoSt` actor code to be more correct and handle all edge cases (early submission, etc)
- [ ] recovery from >1 unexpected faults during consecutive challenge windows
- [ ] consensus penalty for reported faults (if more than just loss of power)
- [ ] consensus penalty for missing PoSts (if more than just loss of power)
- [ ] repeatedly faulty sectors must become eligible for deal arbitration by clients

**Comment by mhammersley** [comment]
not sure if you're planning on addressing these at the same time, @dignifiedquire, but these questions seem potentially relevant, too, and i'm not sure you've seen them yet:
- https://github.com/filecoin-project/specs/issues/407
- https://github.com/filecoin-project/specs/issues/408
- https://github.com/filecoin-project/specs/issues/409
