### ISSUE TITLE
Min miner size

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/specs#454]
Given
1. the way in which TipSets work,
1. the way in which slashing works
splitting your power over as many identities as possible is a beneficial strategy as a miner (and we should assume all miners will do so with an equilibrium being found based on gas costs which make setting up a new identity costly).

What is the minimum size of a miner?

**Comment by anorth** [comment]
There is also a "per-capita" pledge collateral requirement, much more expensive than the gas costs. https://github.com/filecoin-project/specs/blob/master/actors.md#commitsector

**Comment by sternhenri** [comment]
Note that as of v1.2 of their white paper, spacemesh has a 250GB space req for miners.
