### ISSUE TITLE
Add status to sections of the spec

### ISSUE THREAD

**Issue by pooja** [filecoin-project/specs#459]
Currently, it can be difficult to tell the level of stability and completion of various parts of the spec. It would be great to add status indicators so consumers of the spec can understand what is stable and where there be dragons ahead. 

Something like [this](https://github.com/libp2p/specs/blob/master/00-framework-01-spec-lifecycle.md) would be nice

**Comment by sternhenri** [comment]
@pooja can you hold off on this? Would love to take care of this as part of work restructuring the spec that @jzimmerman has been doing :). 

Risks being dup work otherwise.

**Comment by pooja** [comment]
Yes!

**Comment by mishmosh** [comment]
Done in new spec.
