### ISSUE TITLE
Challenges and encoding checks for ZigZag spec

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#46]
This is a proposal to improve the zigzag spec, originally proposed by Ben:
- Have different number of challenged nodes (encoding+inclusion) at each layer
- Have different number of encoding checks at each layer

**Comment by pooja** [comment]
@nicola What's the status on this?

**Comment by whyrusleeping** [comment]
the first point is not going to happen, the second point is already implemented and called the 'tapered construction'.
