### ISSUE TITLE
DRGPorep/Zigzag specs should include graph public params

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#47]
- Graph random seed
- Graph params (e.g.)
  - Graph algorithm choice
  - Depth

**Comment by pooja** [comment]
@nicola What's the status on this issue?

**Comment by whyrusleeping** [comment]
We still need to sample a graph, and include its seed in the spec. This is part of the setup parameters for filecoin.

**Comment by pooja** [comment]
Thanks @whyrusleeping. Is the final version of this not going to be known until much later? Trying to make sure I understand how urgent this issue is.

**Comment by whyrusleeping** [comment]
yeah, this depends on a lot of things. the specific parameters are definitely not figured out yet.

**Comment by mishmosh** [comment]
Stale, we no longer use zigzag.
