### ISSUE TITLE
Network identifier and segregation

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#477]
The spec currently only addresses the possibility of a single Filecoin network (presumably mainnet). In reality, many networks already exist and will continue to exist concurrent with mainnet as various testnets, devnets, etc. Global coordination of at least some of these networks (testnets) is desirable. We must clearly distinguish these networks so that a node knows which network it is operating on, and the existence of many does not unnecessarily compromise the performance of any.

This involved a few pieces:
- a network identifier (name) incorporated into the genesis block (proposed in #456)
- distinct protocol IDs for consensus-related DHT, pubsub, and hello protocols

The go-filecoin team have considered these issues in some depth already as part of running devnets and preparing for an upgradeable network. Please see the discussion in
[protocol upgrade design doc](https://docs.google.com/document/d/17VsfFQk1mZKJj9gkXgSzIPWZAcVeL7VyNjP-is576e4/edit#) and [hello and protocol versions](https://docs.google.com/document/d/1w8ki-7EGaqk41Vbjn4tHLeEVQIjhIzHOCcPXiT8mLRM/edit?pli=1#)

A network name in the genesis block (e.g. in the `Init` actor state) provides a clear label for each network. This supports different networks having different upgrade schedules and easily extends to ad-hoc networks for testing and private use.

Including the network name in the libp2p protocol names prevents concurrent networks from interfering with each other. A node process will be processing only a single logical network at a time. Routing records, block/message pubsub, and hello connections from other logical networks are unwanted noise. While the network should of course be robust to such pollution, inviting it makes analysis and debugging  unnecessarily difficult. A simple way to achieve this is to embed the network name in each protocol string or pubsub channel, e.g. `/fil/apple/hello/1.0.0` or `/fil-apple/hello/1.0.0` (where `apple` is the network name). (This does not preclude co-location of multiple nodes on different logical networks, should that be desired).

Some protocols, such as the point-to-point deal protocol, probably do not require such segregation.

**Comment by pooja** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Network identifier and segregation](https://trello.com/c/Lkm3FI0K/6-network-identifier-and-segregation)

**Comment by anorth** [comment]
See #456 for part of the solution.

@zixuanzh @jzimmerman for addition into the new Init Actor?

**Comment by mishmosh** [comment]
This is now part of the updated hello protocol #847.
