### ISSUE TITLE
Typo in pledge collateral spec

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#499]
right before 'dealing with undercollateralization' there appears to be a typo

`minerPlegeCollateral := availableFil * ( POWER_COLLATERAL_PROPORTION * minerPower / totalNetworkPower PER_CAPITA_COLLATERAL_PROPORTION / numMiners)`

**Comment by mishmosh** [comment]
Closing because can't find this anymore (or even the cue 'dealing with undercollateralization'. Probably got wiped in the Great Spec Overhaul of Sept 2019.
