### ISSUE TITLE
Effort: Outline the Repair protocol v0

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#5]
The repair protocol is written abstractly in the paper.

What I want to get out of this:
- A simple Repair protocol without erasure coding
- This finds missing proofs and triggers `penalize`
- This finds missed assignements (too many proofs missing) and reintroduces the order
- Describe how the order can be picked (since there is no client doing delivery of the file), hence this is a non-standard process for making deals

**Comment by pooja** [comment]
Has been replaced with repair miner work, which is in #230
