### ISSUE TITLE
Spec for Filecoin<-->IPFS Interop

### ISSUE THREAD

**Issue by momack2** [filecoin-project/specs#57]
A product ask that came up during the hackathon yesterday was how to enable IPFS-based dapps to seamlessly use Filecoin to incentivize distributed hosting of their existing IPFS projects. Many of our current community members are builders of dapps (ex OpenBazar), but currently host their own centralized pinning nodes to make their content accessible. When Filecoin launches, many of these partners will likely try to use Filecoin as a replacement/additional hosting mechanism for their existing IPFS dapp. This process should be seamless and not require reconfiguring/rebuilding their application, downloading all their content locally, or change any end-user-visible routing/links. We should figure out what the MVP for initial launch should be and make sure iterations are on our roadmap as the network gets more performant for dapp hosting needs.

**Comment by pooja** [comment]
Closing in favor of #143
