### ISSUE TITLE
Link not found.

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/specs#577]
![image](https://user-images.githubusercontent.com/53922818/67175048-1ec1cd80-f3f7-11e9-839a-3812b48ea8d7.png)

should be:
```text
(You can see the _old_ AccountActor [here](docs/systems/filecoin_vm/sysactors/account_actor_old) )
```

![image](https://user-images.githubusercontent.com/53922818/67175063-313c0700-f3f7-11e9-9db9-b9c519d1ad50.png)

should be:
```text
(You can see the _old_ InitActor [here](docs/systems/filecoin_vm/sysactors/init_actor_old) )
```

**Comment by mishmosh** [comment]
These `.md` files no longer exist since a big actors overhaul. But while investigating this I found more broken actor links in the website rendering, which are fixed in https://github.com/filecoin-project/specs/pull/861.
