### ISSUE TITLE
Automatic draft publishing

### ISSUE THREAD

**Issue by jbenet** [filecoin-project/specs#581]
- The spec uses `ipfs` to publish drafts
- websites like github.com/ipfs/website use some tooling to render + publish to ipfs per PR (see below)
- This would be useful for people to see the rendered output in a PR (and make sure it _can_ be published).

---

Example from: https://github.com/ipfs/website/pull/319 (click "show all checks" in the "All checks have passed" section).

![image](https://user-images.githubusercontent.com/138401/67234386-e1ab0a80-f3f9-11e9-9e62-688a8e2b0871.png)

**Comment by andrew** [comment]
The code for that integration is here: https://github.com/ipfs-shipyard/ipfs-dns-deploy when using Circleci for running tests, built by @olizilla

**Comment by olizilla** [comment]
I am working on adding this today. Adding it as a github action to integrate with the existing workflow.

Do we also want to migrate it from gh-pages to Fleek or our own dnslink update style publishing?
