### ISSUE TITLE
Automatic `make publish` on merge

### ISSUE THREAD

**Issue by jbenet** [filecoin-project/specs#587]
Would be nice to have a Github Action or CI thing to automatically run `make publish` on merge

**Comment by mishmosh** [comment]
Related to #264

**Comment by jimmylee** [comment]
PR is live here: https://github.com/filecoin-project/specs/pull/884

+ need to resolve: `cannot find module providing package crypto/ed25519`
+ need to test `make publish`

**Comment by jimmylee** [comment]
Auto deployment is now supported, tested with: https://github.com/filecoin-project/specs/pull/885

<img width="601" alt="Screen Shot 2020-02-16 at 2 11 39 PM" src="https://user-images.githubusercontent.com/310223/74613782-459ec080-50c6-11ea-8ce9-84d508c92a9a.png">
