### ISSUE TITLE
Document datastructures for sector set storage

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#59]
Currently in the spec, we assume the existence of a 'sector set' datastructure for various operations.

There are two different types of 'sector sets' that are needed. One is simply an ordered set of all the hashes, and the other is a bitfield that selects sectors out of that ordered set in a very compressed way. We need to document how each of these is implemented.

**Comment by whyrusleeping** [comment]
being worked on in https://github.com/filecoin-project/specs/issues/116

**Comment by pooja** [comment]
Closed in favor of #116
