### ISSUE TITLE
Effort: Figure out smallest unit of storage to account for

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#6]
Several function calls take `Size` as an input, where `Size` is the storage size:

- What is the minimum Size we want to account for?
- Should I be able to store 1GB and 1byte or would that round up to 1GB and 1kb or to 1GB and 1MB?
- Would this choice compromise the size that we will end up writing on chain (and if we choose bytes), then we end up having incredibly huge numbers?

I don't think I can find an answer myself, need more tech/optimiziation people like @whyrusleeping or @Stebalien to tap on this!

**Comment by whyrusleeping** [comment]
I think this question (for now) boils down to what units do we want to measure power in. Not many other 'sizes' go on chain.

So, for power, we likely want to use lcd of the potential sector sizes as our base unit. I would feel comfortable calling this 1GB (2^30), but am open to others saying it should be smaller. cc @porcuquine @laser @nicola

**Comment by porcuquine** [comment]
1GiB is also my conservative fallback, so call this a second.

**Comment by dignifiedquire** [comment]
- `1GiB` seems reasonable given the current information I have as the minimum size for power accounting
- For other sizes we still need the `byte` level afaict

**Comment by whyrusleeping** [comment]
Alright, the minimum unit for representing power (for now) is a gigabyte.

**Comment by porcuquine** [comment]
I should have mentioned this earlier, but the current devnet implementation uses 256Mib sectors, so we'll either need to have that diverge from power units (not sure how to reconcile), lower the minimum unit, or stop supporting that sector size. I'd actually like the answer to be the last, and we're moving in that direction. But it's possible we'll have roadblocks (like if larger sectors are inconvenient and get pushback). This might not be a spec issue, but it's at least relevant to a short-term implementation.

**Comment by whyrusleeping** [comment]
@porcuquine yeah, we can hold off on making this change until things settle down on the proofs front.

**Comment by laser** [comment]
Note: Both go-filecoin and rust-fil-proofs support two sector sizes, currently: 1KiB and 256MiB. We could modify the reference implementation's minimum sector size to be 1GiB, but that is going to complicate development somewhat in both projects.
