### ISSUE TITLE
Something's not right. The chain.id file was not found.

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/specs#618]
build from : 19af81cf312f44dd76255f495960e4eaf5f63e9b

![image](https://user-images.githubusercontent.com/53922818/68014527-d219a480-fcca-11e9-9303-321af3df7bf5.png)

**Comment by mishmosh** [comment]
Thanks for the report! This is fixed now: https://filecoin-project.github.io/specs/#systems__filecoin_blockchain__struct__chain
