### ISSUE TITLE
Verifiable markets for Filecoin v1

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#63]
- [ ] TODO: elaborate on what this means and what decisions are needed

**Comment by whyrusleeping** [comment]
to clarify, the current design is 'verifiable enough' to meet constraints

**Comment by pooja** [comment]
We have done enough for launch, but more work needed for longer-term

**Comment by mishmosh** [comment]
> The amount of storage locked up for asks should be verifiable
Done, via CommittedCapacity

> Client bids have funds verifiably locked up for them
Done

> The money exchanged in a given storage deal is globally verifiable
Done
