### ISSUE TITLE
Treasury actor code for block reward

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#665]
In the implementations right now, the network treasury (from which block rewards are paid) is a simple account actor, and the block reward transfer from it an implicit operation.

A single transfer is too simple for the block reward if we have a dynamic collateral model (e.g. as a function of money supply), since miners may become under-collateralized simply through inaction. Our proposal for remedying this is to garnish the block reward to make up any required pledge collateral, paying the remainder to the miner owner. A good place to express this logic would be in the treasury actor (otherwise it has to be special sauce in the VM interpreter). Then the block reward would be represented as an implicit message to the treasury actor (like the implicit process-election-post message) – #662 does this but the actor to call doesn't yet exist.

Note that we probably need the treasury to be a real actor anyway for disbursement of vesting tokens #391 #507 (unless we use a separate actor for that).

FYI @zixuanzh @whyrusleeping

**Comment by anorth** [comment]
Note that filecoin currently has an invariant that top-level messages come from account actors. This means the message to the treasury actor must be sent from another account, such as the block miner's worker account. We would need a mechanism to prevent the message being invoked explicitly, though.

An alternative would be to instantiate a new account actor (with zero balance, no methods, and empty pubkey address) specifically for the purpose of originating implicit network messages.

**Comment by whyrusleeping** [comment]
Im not sure where the account actor source requirement comes from (its possible to set the source actor to whatever you want when invoking the vm directly).

The difficulty around preventing the calls from normal users can be resolved by requiring the caller to equal the block miner (the actor address) and for us to set the from actor in the invocation to the miner actor creating the block

**Comment by anorth** [comment]
I wouldn't say it's a requirement, but it's currently always the case and simplifies some things like knowing whether to inc the CallSeqNum. Should we inc the miner actor's CallSeqNum? We were considering not even having it on non-account actors. We could break the convention tho.

Your proposal to use the miner _actor_ address would break that convention. But if we're going to break it, we may as well have the treasury actor invoke itself?

So options:
- use the miner worker, add mechanism to prevent explicit invocation, retain convention
- use a new network account actor as the sender, retain convention
- use the miner worker as the sender, break convention, need some mechanism to prevent unwanted invocation?
- treasury actor invokes itself, break convention, easy to to prevent unwanted invocation

**Comment by whyrusleeping** [comment]
Miner actor invoking it seems fine. Incrementing its nonce is weird but not really much of a problem

**Comment by jzimmerman** [comment]
A couple of notes --
- It seems like a lot of these problems would be resolved if we had a separate SystemActor (or ControlActor? not sure about the nomenclature). Then this actor could be the sender of all these privileged messages, and it could trigger behavior by sending messages to Treasury, Cron, and so forth, without worrying about having such messages send by nonprivileged actors.
- We should be clear on the semantics of CallSeqNum. As I understand it right now, an actor A should have a CallSeqNum if (and only if) it can possibly act as an OriginalSender. So we could, for example, have ControlActor and AccountActors be the only ones with this property.

**Comment by anorth** [comment]
System actor added as the sender of these messages in https://github.com/filecoin-project/specs/pull/721

**Comment by mishmosh** [comment]
@anorth #721 has been merged, does that fully resolve this issue? if yes please close.

**Comment by anorth** [comment]
The real work was to write the RewardActor, but since that's partially there and moved to specs-actors, we can close this now.
