### ISSUE TITLE
Effort: Figure out the smallest amount of Filecoin to represent

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#7]
If Filecoin is infinitely divisible.. what is the smallest unit of Filecoin that we want to represent in the code?

Calling @jbenet, @Stebalien, @whyrusleeping, @dignifiedquire

**Comment by pooja** [comment]
We've chosen to go with 10^-18 for now (attoFil).

If someone wants to talk about changing this, feel free to re-open the issue!
