### ISSUE TITLE
Document builtin actors in the spec

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#71]
As part of a full implementation of filecoin, anyone re-implementing the protocol will need to also re-implement the built-in network actors. They must be implemented *exactly* the same way, and always produce the exact same output, otherwise the two implementations will fail to come to consensus.

We need to come up with a good language agnostic way to describe, in exact detail, the exact functionality of each method for each actor, including their storage.

**Comment by pooja** [comment]
@anorth What do you think about this issue?

@whyrusleeping Are you referring specifically to account, miner, paymentBroker, and storageMarket actors?

**Comment by anorth** [comment]
I agree with the issue description and @whyrusleeping's recommendation that, until we're highly confident in the actor implementations, we defer attempting another form of specification.

I think it would be helpful for the spec to enumerate the actors and outline their general roles, but then point to the code.

**Comment by pooja** [comment]
Sounds great. We can move forward with this then:

1. Spec should enumerate the actors and their general roles
2. For miner, account, paymentBroker, and storageMarket actors, the spec should point to the current go-filecoin implementation

@anorth Double-checking that init and multisig account actors still need to be implemented in the gfc implementation, right?

**Comment by anorth** [comment]
That's correct

**Comment by whyrusleeping** [comment]
Had a conversation with @gnunicorn and @dignifiedquire and we're pretty confident that we can write pseudocode in the spec that is clear enough that two independent implementations from the spec will end up with the same functions (same inputs map to same outputs). Most of the logic is just basic conditionals and math. Things like iteration order can be stated explicitly, and the datastructures are already defined elsewhere.

I will take this on soon.

**Comment by dignifiedquire** [comment]
basics are done, improvements coming soon
