### ISSUE TITLE
Filecoin node 'op-log'

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#72]
Filecoin nodes should remember many of the actions they make, all storage operations, all payments, all retrievals.

We should document what data is logged, and how.

This is part of 'document local node storage'

**Comment by mishmosh** [comment]
I think this is more properly part of node design, and doesn't have to be required by protocol. In the year since this was created I think the implementations have a plan for remembering many of the actions now.

Feel free to reopen if there's more to discuss.
