### ISSUE TITLE
Should system actor's CallSeqNum be incremented?

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#761]
The system actor is the `From` for implicit system messages which are constructed directly by the interpreter: election post processing, block reward, and cron tick. It's specced as a singleton account actor (though I expect it to have an empty/invalid pubkey address, so that it can never be impersonated). This preserves invariants that:
- every top-level message is originated by an account actor
- every actor has state in the state tree, keyed by address

Another current invariant is that the CallSeqNum on the account actor originating a message has its `CallSeqNum` incremented immediately before invocation, and the current spec code does that too. However:
- the system actor's CallSeqNum is never inspected or checked, because the value is just set to be correct immediately before the message is executed
- incrementing it causes a write to the actor's state which is ultimately of little value

So we could special-case the system actor in the interpreter and skip the CallSeqNum bump. This would remove a few lines of code from the spec's interpreter: loading the system actor to determine the correct value when constructing a message, and incrementing it.

Note other possibilities could break other invariants too:
- we could add a new actor type for the system actor
- we could avoid the actor or its state entirely, specifying only a system address to be used as `From`, but which is absent from the state tree

Both of these would be more complex in the strict sense of requiring more language to describe the special cases and qualify the invariants.

See also #665 
cc @icorderi @jzimmerman

**Comment by mishmosh** [comment]
@anorth has this been confirm in the latest actor work?

**Comment by anorth** [comment]
This is outside the scope of the actors, and I don't think has been resolved.

I think there was some enthusiasm for the alternatives.

**Comment by anorth** [comment]
We created a distinct system actor type and resolved not to inc the nonce for any actor other than accounts.
