### ISSUE TITLE
Please add .car file diagram to spec

### ISSUE THREAD

**Issue by vmx** [filecoin-project/specs#770]
Hey @mishmosh could you add the diagram from slide 5 ".car — Certified ARchives" (the presentation that was also used in https://github.com/filecoin-project/specs/pull/729) to the spec. I found that I reference to and look at it a lot recently.

**Comment by mishmosh** [comment]
You got it!

**Comment by vmx** [comment]
It's part of https://github.com/ipld/specs/pull/230 now, hence closing this issue.
