### ISSUE TITLE
Account actor caller type validation breaks use of multisig actors

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#780]
Some methods on the storage market and power actors require that their caller be an account actor:

```
rt.ValidateImmediateCallerAcceptAnyOfType(actor.BuiltinActorID_Account)
```

This makes it impossible to use multisig actors as principals, making them all but useless.

In general, objects and functions that make assertions about who uses them an how are very brittle, since the developer cannot predict all the useful ways something might be used. IMO objects should define clear semantics and invariants about their behaviour, and be unopinionated about how they might be composed into a larger system. However, I understand there may be some legitimate defence-in-depth value to some such checks (just not for account actors).

**Comment by mishmosh** [comment]
@anorth is this still relevant?

**Comment by anorth** [comment]
The immediate problem was fixed manually. I've resigned that my more general statement is overridden by arguments of defence in depth.
