### ISSUE TITLE
Decouple VM interpreter from storage miner actor state for owner lookup

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#787]
The VM interpreter currently has a dependency on the storage miner actor state. It uses this to lookup the owner address corresponding to the miner actor address associated with each block, in order to pay gas rewards to the owner. This is an unfortunate coupling between an otherwise generic VM and Filecoin application semantics.

It could be avoided by:
 - paying gas rewards via the RewardActor, which can do the miner->owner lookup (#781)
 - resolving all miner->owner mappings in the state before invoking interpreter (e.g. during validation) and passing them in
 - paying rewards to the miner actor instead of owner (with some miner->owner withdrawal mechanism)
 - including the owner address in block headers (and requiring it match the block's miner as part of semantic validation)

**Comment by zixuanzh** [comment]
closed by #859
