### ISSUE TITLE
Abstract BlockHeader type from actors for consensus fault slashing

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#791]
At present, the storage power actor imports the BlockHeader type for use as parameters to the exported `ReportConsensusFault` method. The logic for consensus fault validation requires inspecting some fields (miner address, height) and validating the block headers' signatures. It also requires access to the blocks' parent tipset, access to which hasn't been resolved either in the spec or implementations yet.

This is the only reason that the blockchain types are visible inside the VM. In my opinion it would be well worth the effort to break this dependency so that, as systems, the blockchain depends on the VM (for computing state) but never the other way around. The runtime should serve as the abstraction to the outside world, hiding as much as possible, including the blockchain, as it does for sampling randomness.

One simple way to do this would be to change the `ReportConsensusFault` to accept uninterpreted byte arrays for the block header parameters and pass them directly to a `CheckConsensusFault` method on the runtime. The VM implementation can have access to blockchain types and the chain history to implement all the logic in one place.

CC @zixuanzh @whyrusleeping

**Comment by zixuanzh** [comment]
closing as this has been added in specs-actors, https://github.com/filecoin-project/specs-actors/blob/7ebc172946404fadbeb42c5cb8f20bfb58236ec9/actors/builtin/storage_power/storage_power_actor.go#L371
