### ISSUE TITLE
Add NetworkID to ID/address creation

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/specs#808]
Lost in https://github.com/filecoin-project/specs/pull/802/files.

New IDAddresses need networkID in them. Likely means a change to go-addresses.

**Comment by anorth** [comment]
I checked with @whyrusleeping about this before #802. The current implementation uses the network ID only when rendering, it's not actually represented in the serialized address. To the extent the spec was supposed to represent the existing implementation, _that_ was lost in translation.

If we want to properly represent it in the address, we need to add it to all address types.

**Comment by sternhenri** [comment]
Mmmh. I understand. Thanks for the update. If it isn't deemed necessary by impls, I'm fine to lose it. I see its utility of course, but in the interest of ship... I'll close this unless deemed necessary to reopen.
