### ISSUE TITLE
Feedback for "Retrieval Market V0"

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/specs#81]
> What is the Retrieval Market
> What the Retrieval Market affects
> Dependencies

These sections are empty. Some motivation for the Retrieval Market would be good. It would also be good to have some specific non-goals of V0 that are to be addressed in V1.

>  Once the client has received all the data, it should then send a payment channel SpendVoucher of the proposed amount to the miner.

The spec should establish how the payment channel has come into being. It should probably also mention that the miner should confirm its existence prior to to accepting a retrieval deal.

> ... streamed as a series of bitswap block messages, using a pre-order traversal of the dag....

What dag? Why is it needed to transmit blocks?

> Retrieval miners should also support a query service that allows clients to request pricing information from a miner.

The spec should be clear on whether this service is going to be specified or left up to implementations.

> Retrieval Market Commands

Specifying UX at this level of detail (or at all?) seems inappropriate for the spec.

**Comment by mishmosh** [comment]
The new Retrieval Market spec (https://filecoin-project.github.io/specs/#systems__filecoin_markets__retrieval_market) addresses all of these, I believe. Feel free to reopen if not.
