### ISSUE TITLE
Spec Numbering is off

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/specs#813]
In different sections, section/subsection numbers are off (e.g. 2.7 in the TOC might read 2.9). I suspect this is due to how the numbering is done in both places, and [Hugo's](https://gohugo.io/) response to markdown headers...

**Comment by mishmosh** [comment]
Example: section 2.7.2.1.

**Comment by mishmosh** [comment]
A debugging hunch from @sternhenri via chat:
> Slightly unrelated but something to note on the numbering of the sections: I believe that it is both that which is taken by the ordering of the entries, but also that adding headers in the md, ie # title, ## title , etc also causes numbers to be enumerated at build time which is why if you look the numbers in the ToC are off as compared to those in the doc itself. (my best guess). In case ever useful.
