### ISSUE TITLE
Feedback: Retrieval Market

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/specs#84]
> The v0 retrieval market will initially be implemented as two libp2p services.

It's not immediately clear what the two services are (RetreivalDealPropsoal, and RetreivalQuery). Also, to implement them, we will need libp2p protocol IDs.

In the RetreivalDealPropsoal, we describe a payment as PaymentInfo. However, under network-protocols PaymentInfo described as payment for provable data within live sectors, and requires a set of predetermined payments. This would appear to be a different kind of PaymentInfo, that uses SpendVouchers instead of PaymentVouchers?

> Chain Based Content Routing

Is this section really needed? It appears to mostly be related to the UX, and nothing to do with the Retrieval Market itself. As the spec is written at the moment there is an assumption that a connection is already made to the peer. Should the spec cover how to open a connection to a peer? If we want to include that information, then I think this might make more sense to also specify how to find the miner / peer which is storing the content.

> Retrieval Market Commands

I don't believe these should be part of the spec, as they have nothing to do with the network itself.

**Comment by mishmosh** [comment]
Retrieval market spec was drastically overhauled in #648. If you feel this aren't sufficiently addressed, feel free to reopen.
