### ISSUE TITLE
Missing .id files notification (due to conversion to go code)

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/specs#843]
I went looking for something on the specs website, and got confused by several messages that say:

`Something's not right. The storage_deal.id file was not found.`

Or something similar.

I think that happened cause these files got converted to go code. It would be nice to go back and fix those links, cause in some cases the only way to get back to those files is to download the repo.

**Comment by mishmosh** [comment]
Thanks for the report. Fixed in #849 and looks correct on the website now.
