### ISSUE TITLE
better algorithm for SampledSectors calculation

### ISSUE THREAD

**Issue by steven004** [filecoin-project/specs#848]
This algorithm is not fair and may bring more stress to the network: 
`numSectorsSampled = ceil(len(provingSet) * EPoStSampleRate`

Suggest change this to: 
`numSectorsSampled = f(len(provingSet) , EPoStSampleRate, height)`

An example: 

```
func f(lps, esr, height)  uint { 
    t := hash(miner_address || height)
    m := lps /  EPoStSampleDiv
    p := lps % EPoStSampleDiv
    if t * EPoStSampleDiv < p * 2^256 { 
         m += 1
    }
   return m
}
```

**Comment by sternhenri** [comment]
Hi @steven004, Thanks for reaching out about this. 

A few questions:
- I assume `EPoStSampleDiv` is `esr` in your alg, right?
- Could you explain to me how you think your algo should work? as is stated in that section of the spec `EPoStSampleDiv` is a fraction (we move to splitting out numerator and denominator later), so it may lead to an extremely high n.

**More importantly, what do you see as unfair about the current process?**
As it is done (from a fix in https://github.com/filecoin-project/specs/pull/723/files#diff-351a78e10f4cc4cce1862d27b75c8f0bR81), the target is set as:
`target = activePowerInSector/networkPower * EC.ExpectedLeadersPerEpoch * numSectorsMiner / numSectorsSampled`

and so the target changes (only this part, let's call it `S = numSectorsMiner / numSectorsSampled` based on the number of sectors sampled for each miner. Miners with fewer sectors sampled will have a lower target (applied to their fewer sectors). This means that on expectation miners will find winning tickets in proportion with the total number of sectors they submit.

For instance:
- take the EPoStSampleRate to be `1/25`, all sectors are of equal size without loss of generality
- miner A has 1 sector --> `numSectorsSampled = 1` --> `S = 1/1 = 1`
- miner B has 24 sectors --> `numSectorsSampled = 1` --> `S = 24/1 = 24`
- miner C has 26 sectors --> `numSectorsSampled = 2` --> `S = 26/2 = 13`

Thus, miner A gets one ticket, miner B gets one ticket whose target is 24 times higher (correct given their 24 times more power than A), miner C gets two tickets each of which has a target 13 times higher (correct given their 26 times more power than A, or 13/12th times more power than B). Does that make sense? Is that what you see in the spec?

**Comment by steven004** [comment]
@sternhenri 
I think `EPoStSampleRate` is defined as 1/25 in the current implementation in Lotus, and here `EPoStSampleDiv` I mean *25*. 

You are right. Sorry, the current algorithm is good. I studied it weeks ago but forgot these days, perhaps due to preparing for the holiday. Thanks for the detailed explanation. 

I am closing this issue.

**Comment by sternhenri** [comment]
Great! Happy New Year @steven004 :D
