### ISSUE TITLE
Hanging phrase in data transfer spec

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs#852]
In: https://github.com/filecoin-project/specs/blob/master/src/systems/filecoin_files/data_transfer/_index.md#request-phases

> Transfer - Once both parties have negotiated and agreed upon, the data is actually transferred. The default protocol used to do the transfer is Graphsync

Agreed upon ??

**Comment by mishmosh** [comment]
maybe "deal terms" or super-literal "once both parties have signed the DealProposal" but defer to @hannahhoward here.
