### ISSUE TITLE
[web] `fillCodeRefs` slow on startup 

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/specs#860]
*This might be an issue of my particular setup, if nobody else is experiencing something similar feel free to close.*

When loading the website https://filecoin-project.github.io/specs/ with Chrome (`Version 79.0.3945.88 (Official Build) (64-bit)`) in Ubuntu 18 it stalls for something like 20-30 seconds with very little responsiveness. The Chrome profiler pointed to

https://github.com/filecoin-project/specs/blob/7e4fde83c7699f8ec33a4c8735768e4bc0bbc6fd/hugo/layouts/shortcodes/js.html#L80-L84

(indicating that "Forced reflow is likely performance bottleneck").

This makes the basic workflow of opening the spec website to do a quick search of a term very slow (even for content that is not loaded through `fillSingleCodeRef`).

**Comment by mishmosh** [comment]
Thanks for the report and sorry for the trouble. I have experienced a similar lag & crash on Chrome for Android (2nd bullet point in #639), but on desktop (Chrome for MacOS 79.0.3945.117 - Official Build 64-bit) it loads within ~2 seconds for me.

I suspect this is relatively unique to your setup but let's leave the issue open to investigate. In the meantime, is there another browser you can use?

**Comment by terorie** [comment]
Can confirm with `fillCodeRefs` taking up over half of the total render time. The side loads quickly regardless, it just causes quite some CPU load.
My browser reports that in `fillSingleCodeRef`, this line
```js
 let origKey = x.innerText;
```
needs layout (for some reason)..



```js
x.innerHTML = "<a class=codeLink href=\"/#go__" + origKey + "\">" + x.innerHTML + "</a>"`
```

invalidates the previous layout (obviously)
and then

**Comment by terorie** [comment]
@mishmosh @schomatis I found the solution
https://github.com/filecoin-project/specs/blob/7e4fde83c7699f8ec33a4c8735768e4bc0bbc6fd/hugo/layouts/shortcodes/js.html#L41

Using `x.textContent` here fixes the errors and layout thrashing and cuts render time by half!

Refer to https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText

> Note: innerText is easily confused with Node.textContent, but there are important differences between the two. Basically, innerText is aware of the rendered appearance of text, while textContent is not.

We don't need the rendered text, just the actual content.

**Comment by mishmosh** [comment]
@terorie just for the record, which browser and os are you using?

**Comment by terorie** [comment]
@mishmosh `Version 79.0.3945.130 (Official Build) snap (64-bit)` on Ubuntu 20.04
