### ISSUE TITLE
Discussion: Swapping git-submodule for our hugo/book theme.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/specs#882]
# Introduction

Hey everyone! Really honored to work on the spec. 🙏

Currently on our [Filecoin specification website](https://filecoin-project.github.io/specs/) I would like to make adjustments to the theme without sending PRs to the [root repository](https://github.com/alex-shpak/hugo-book/tree/74422e68968594f7f910aab25ebbf54dcf0181b2). 

So I want to fork the submodule.

### What kind of changes Jim?

<img width="1592" alt="Screen Shot 2020-02-12 at 10 09 54 AM" src="https://user-images.githubusercontent.com/310223/74365448-fb92a380-4d82-11ea-8cd7-3ffc7eb35bc9.png">

+ Search doesn't work. We should just take it out and reintroduce something else.
+ I want to tighten the typography up, maybe get it closer to [Lotus documentation](https://lotu.sh) since we pay for [GT Zirkon](https://www.grillitype.com/typeface/gt-zirkon) or use:

```css
font-family: -apple-system, BlinkMacSystemFont,
                     'avenir next', avenir,
                     helvetica, 'helvetica neue',
                     ubuntu,
                     roboto, noto,
                     'segoe ui', arial,
                     sans-serif;
}
```

### How are you going to do it, Jim?

Here are our current submodules.

```sh
[submodule "orient"]
	path = orient
	url = https://github.com/filecoin-project/orient.git
[submodule "hugo/themes/book"]
	path = hugo/themes/book
	url = https://github.com/alex-shpak/hugo-book
[submodule "src/actors"]
	path = src/actors
	url = https://github.com/filecoin-project/specs-actors.git
```

I will replace `https://github.com/alex-shpak/hugo-book` with `https://github.com/filecoin-project/hugo-book` or `https://github.com/filecoin-project/filecoin-spec-theme`.

### I have thoughts, whats next?

+ Let me know what you think about the idea!
+ If the sentiment is positive I'm just going to do it.

**Comment by mishmosh** [comment]
- Agree on removing broken search. We can even remove it and replace it with nothing, because the single-page rendering means you can use web browser search.
- Typography: typography styles should be consistent across lotus docs, Filecoin metadocs, filecoin website (not in this issue).

I'm a bit wary of forking the submodule but not totally opposed. Are you willing to sign up for permanent maintainership/updates of the new submodule.

It's exciting that you are thinking about this site holistically! But neither of these proposed changes are higher priority than #587; we need to solve that first.

**Comment by jimmylee** [comment]
Thanks for the response 👍 Acknowledged.

I am willing to sign up for permanent maintainer-ship of the submodule, and even the eventual overhaul of the specs website if it ever came to it.

I am happy to work on #587. My intent here was to work on incremental tasks to familiarize with the repository more.

**Comment by jimmylee** [comment]
Work for #587 is in progress here: https://github.com/filecoin-project/specs/pull/884

+ need to resolve: `cannot find module providing package crypto/ed25519`
+ need to test `make publish`

**Comment by jimmylee** [comment]
PR for #587 is ready for review: https://github.com/filecoin-project/specs/pull/887
