### ISSUE TITLE
RFP Draft for Storage-based Proof Work

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/specs#9]
More details: https://docs.google.com/document/d/12I9RqaHp331MtLb8p8BjLyKE7MiLzgEY5w6m3HWN_OM/edit can be found here.

- [ ] Details on the seal function
- [ ] More context on the proofs
- [ ] Define interfaces for the library
- [ ] Describe the circuits as NP statements

**Comment by pooja** [comment]
Closing as non-actionable
