### ISSUE TITLE
transaction/message versioning

### ISSUE THREAD

**Issue by jleni** [filecoin-project/specs#913]
At the moment, CBOR txs lack any kind of versioning support. Any changes to fields, or types may result in applications to incorrectly parse messages or transactions.
A very explicit example are airgapped devices or hardware wallets that are not frequently updated.

While unlikely, if the serialization format changes, it is possible that older implementations could still parse the data and show incorrect or unintended values.

I would recommend adding a few versioning bytes at the beginning of each tx / message.

**Comment by mishmosh** [comment]
Thanks for the suggestion, will be coming to implementations in the next few weeks.

**Comment by anorth** [comment]
FYI @ZenGround0 , @icorderi
