### ISSUE TITLE
Resume mining after being slashed

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#92]
If a miner fails to submit their PoSt in time, they can be slashed. Currently this means they lose all of their (EDIT: storage) collateral. However, it does not mean they have actually lost all of their data. A miner should be able to re-up on their collateral, and continue mining.

A 'simple' way to do this would be to simply require that miners send enough funds along with a normal submit PoSt call to 'resume' mining.

Also, this means that clients cannot call arbitrate deal after a miner has been slashed for not submitting their PoSt. There should be some period of time defined after which miners can be assumed to have actually lost the data.

**Comment by mishmosh** [comment]
This is now possible with temporary faults.
