### ISSUE TITLE
The payment_channel_actor.id file was not found

### ISSUE THREAD

**Issue by tcharding** [filecoin-project/specs#924]
Section 2.5.2.1 (https://filecoin-project.github.io/specs/#systems__filecoin_blockchain__storage_power_consensus) contains this error

`Something's not right. The payment_channel_actor.id file was not found.`

**Comment by snario** [comment]
Presumably should be linking to something related to [this code](https://github.com/filecoin-project/specs-actors/tree/master/actors/builtin/paych).
