### ISSUE TITLE
Update hashes to be blake2b

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/specs#926]
I'm not sure how many such updates will need to be made, we know that ticket creation and verification has been changed to use blake2b.

**Comment by anorth** [comment]
This sounds like a duplicate of #897.

By changed, do you mean changed from [this resolution from February](https://github.com/filecoin-project/specs/issues/862#issuecomment-582368223)?  Why did it change? Who changed it?

cc @dignifiedquire @porcuquine @ZenGround0 @whyrusleeping

**Comment by arajasek** [comment]
Yup, definitely a duplicate, sorry...I called it "changed" because go-filecoin already uses blake2b, and there seems to be general consensus that Lotus can do the same without a problem.

Closing this, #897 can stay as the place for discussion (and the tracker for any update that ends up being made).
