### ISSUE TITLE
Improve spec for external consumption

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/specs#933]
Throughout the month of June some people are going to be looking at the Lotus code base, we should provide clear documentation to support that effort, in part by having the spec in shape for external consumption. The main component we need to review are:

* General introduction to the architecture.
* Actors.
* Markets.
* Consensus.
* Proofs.
* Networking (should not overlap with libp2p).

At least the introduction and actors should be ready before the start of the month and the rest of the contents should be continuously delivered throughout.

This issue will track all other issues comprehended by this effort (and should be closed by the end of June, independently of the state of its child issues).

* Specification introduction and overview: https://github.com/filecoin-project/specs/issues/932.
* Systems: https://github.com/filecoin-project/specs/issues/936.

**Comment by hugomrdias** [comment]
old issue gonna close this, feel free to reopen
