### ISSUE TITLE
Review spec systems

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/specs#936]
- [ ] node types: https://github.com/filecoin-project/specs/blob/master/src/systems/filecoin_nodes/node_types/node_types.md

- [ ] IPLD store: https://github.com/filecoin-project/specs/blame/master/src/systems/filecoin_nodes/repository/ipldstore/_index.md#L19

- [ ] update libp2p spec links (like gossipsub): https://filecoin-project.github.io/specs/#systems__filecoin_nodes__network

- [ ] explain with *human* text the VM architecture (key part in the entire system): https://filecoin-project.github.io/specs/#systems__filecoin_vm

- [ ] explain with text *all* the major actors, for example: https://filecoin-project.github.io/specs/#systems__filecoin_vm__sysactors__init_actor

- [ ] sync actors list with the specs-actors repo, or link directly there: https://filecoin-project.github.io/specs/#systems__filecoin_vm__sysactors

**Comment by mishmosh** [comment]
Created individual issues for each one, so closing this. Thx @schomatis!
