### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/specs#949]
Some problems have been introduced over recent sprints, causing compilation errors. This is pretty urgent as it affects readability for everyone & workflows for contributors:

- A CircleCI test is failing. Likely reasons:
  - syntax errors in go
  - some files that can’t be found (because renamed or moved to `specs-actors` repo).
- Failure to compile also means that auto-publish doesn’t work, so specs website is out of date.

**Comment by mishmosh** [comment]
Reported by @hugodias:

```
algorithms/crypto/randomness.go:11:2: module github.com/filecoin-project/specs-actors@latest found (v0.5.6, replaced by ../../src/actors), but does not contain package github.com/filecoin-project/specs-actors/actors/abi/big
systems/filecoin_blockchain/struct/block/election.go:6:2: no matching versions for query "latest"
make: *** [build-code] Error 1
```

This is likely due to `.id` files. cc @zixuanzh suggests removing id files entirely.

**Comment by hugodias** [comment]
Hey, @mishmosh I'm not related to this project. 

I'd say I never used it and also never reported such a problem.

**Comment by mishmosh** [comment]
@hugodias apologies, wrong handle!

**Comment by nonsense** [comment]
Fixed in https://github.com/filecoin-project/specs/pull/954 and https://github.com/filecoin-project/specs/pull/955
