### ISSUE TITLE
Search isn't working through the gateway

### ISSUE THREAD

**Issue by hugomrdias** [filecoin-project/specs#993]
check https://beta.spec.filecoin.io/ 
<img width="961" alt="Screenshot 2020-07-20 at 12 40 29" src="https://user-images.githubusercontent.com/314190/87934028-36151080-ca86-11ea-9dee-aa49ed66a4e7.png">

**Comment by olizilla** [comment]
is work for me... are you still seeing the issue @hugomrdias ?
<img width="979" alt="Screenshot 2020-07-21 at 11 04 18" src="https://user-images.githubusercontent.com/58871/88041220-fe6b9e80-cb41-11ea-896d-46522ebeafea.png">

**Comment by hugomrdias** [comment]
its magic !! Beautiful should we remove netlify now ?

**Comment by olizilla** [comment]
if it works for you then yes! All systems IPFS.
